import { useEffect, useRef, useState } from "react";
import { claimMonitoringSession, heartbeatMonitoringSession, releaseMonitoringSession, setCameraMonitoring, startMonitoringEpisode, submitMonitoringSample, type OperationsCamera, type LiveObservation, type MonitoringLease } from "../../services/api/operations";
import { loadAuthenticatedMedia, releaseAuthenticatedMedia } from "../../services/api/media";
import "./camera-monitor.css";
import "./camera-monitor-overlays.css";
import "./camera-monitor-labels.css";

type Props = { camera: OperationsCamera; embedded?: boolean; onObservation?: (observation: LiveObservation) => void };

function frameFromVideo(video: HTMLVideoElement, name: string) {
  return new Promise<File>((resolve, reject) => {
    if (!video.videoWidth || !video.videoHeight) { reject(new Error("A source frame is not available yet.")); return; }
    const canvas = document.createElement("canvas"); canvas.width = video.videoWidth; canvas.height = video.videoHeight;
    canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height);
    canvas.toBlob((blob) => blob ? resolve(new File([blob], name, { type: "image/jpeg" })) : reject(new Error("The browser could not encode the sampled frame.")), "image/jpeg", .82);
  });
}

function boxStyle(box: { x1: number; y1: number; x2: number; y2: number }, image: { width: number; height: number }) { return { left: `${box.x1 / image.width * 100}%`, top: `${box.y1 / image.height * 100}%`, width: `${(box.x2 - box.x1) / image.width * 100}%`, height: `${(box.y2 - box.y1) / image.height * 100}%` }; }
function issueBox(issue: LiveObservation["issues"][number]) { const geometry = issue.geometry; if (!geometry || typeof geometry !== "object" || !("bbox" in geometry)) return null; const box = (geometry as { bbox?: unknown }).bbox; if (!box || typeof box !== "object") return null; const value = box as Record<string, unknown>; const x1 = Number(value.x1), y1 = Number(value.y1), x2 = Number(value.x2), y2 = Number(value.y2); return [x1, y1, x2, y2].every(Number.isFinite) ? { x1, y1, x2, y2 } : null; }

export function CameraMonitor({ camera, embedded = false, onObservation }: Props) {
  const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | undefined>(undefined); const lease = useRef<MonitoringLease | undefined>(undefined); const timer = useRef<number | undefined>(undefined); const heartbeat = useRef<number | undefined>(undefined); const sequence = useRef(1); const sampling = useRef(false); const sourceLoaded = useRef(false); const [sourceUrl, setSourceUrl] = useState<string>(); const [running, setRunning] = useState(false); const [enabled, setEnabled] = useState(camera.monitoringEnabled); const [revision, setRevision] = useState(camera.revision); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [observation, setObservation] = useState<LiveObservation>();
  const stop = async () => { window.clearInterval(timer.current); window.clearInterval(heartbeat.current); timer.current = undefined; heartbeat.current = undefined; sampling.current = false; stream.current?.getTracks().forEach((track) => track.stop()); stream.current = undefined; const current = lease.current; lease.current = undefined; if (current) await releaseMonitoringSession(current).catch(() => undefined); if (sourceLoaded.current) releaseAuthenticatedMedia(`monitor-source:${camera.id}`); sourceLoaded.current = false; setSourceUrl(undefined); setRunning(false); setBusy(false); };
  useEffect(() => () => { void stop(); }, [camera.id]);
  useEffect(() => { setEnabled(camera.monitoringEnabled); setRevision(camera.revision); }, [camera.monitoringEnabled, camera.revision]);
  const loadSource = async () => { if (camera.sourceType === "laptop_camera") { stream.current = await navigator.mediaDevices.getUserMedia({ video: true, audio: false }); if (video.current) video.current.srcObject = stream.current; return; } if (!camera.source?.contentUrl) throw new Error("This looped Camera has no readable source video."); const url = await loadAuthenticatedMedia(`monitor-source:${camera.id}`, camera.source.contentUrl); sourceLoaded.current = true; setSourceUrl(url); };
  const sample = async (currentLease: MonitoringLease, episodeId: string) => { if (sampling.current || !video.current) return; sampling.current = true; setBusy(true); try { const result = await submitMonitoringSample(currentLease, camera.id, episodeId, sequence.current++, await frameFromVideo(video.current, `camera-${camera.id}-sample.jpg`)); setObservation(result.observation); onObservation?.(result.observation); setMessage(`Live · ${result.observation.peopleCount} people · ${Math.round(result.observation.processingTimeMs)} ms`); } catch (error) { setMessage(error instanceof Error ? error.message : "The frame could not be submitted."); } finally { sampling.current = false; setBusy(false); } };
  const start = async () => { if (!enabled) { setMessage("Monitoring is disabled for this Camera. Enable it for a deliberate demo first."); return; } setMessage(""); try { const currentLease = await claimMonitoringSession(); lease.current = currentLease; await loadSource(); const episode = await startMonitoringEpisode(currentLease, camera.id); sequence.current = episode.nextSequence; setRunning(true); heartbeat.current = window.setInterval(() => { void heartbeatMonitoringSession(currentLease).catch(() => { void stop(); setMessage("Monitoring lease expired."); }); }, 10_000); timer.current = window.setInterval(() => { void sample(currentLease, episode.episodeId); }, 1_000); setMessage("Monitoring started: one frame per second."); } catch (error) { await stop(); setMessage(error instanceof Error ? error.message : "Monitoring could not start."); } };
  const toggle = async () => { if (running) await stop(); setBusy(true); try { const result = await setCameraMonitoring({ ...camera, revision }, !enabled); setEnabled(result.monitoringEnabled); setRevision((current) => current + 1); setMessage(result.monitoringEnabled ? "Monitoring enabled. Start it when ready." : "Monitoring disabled."); } catch (error) { setMessage(error instanceof Error ? error.message : "Monitoring setting could not be updated."); } finally { setBusy(false); } };
  const controls = <header><div><span>LIVE MONITORING</span><strong>{running ? "Owner session active" : enabled ? "Ready to monitor" : "Monitoring disabled"}</strong></div><div><button type="button" onClick={() => void toggle()} disabled={busy}>{enabled ? "Disable" : "Enable"}</button><button type="button" onClick={() => void (running ? stop() : start())} disabled={busy || !enabled}>{running ? "Stop monitoring" : "Start monitoring"}</button></div></header>;
  const frame = <div className="current-camera-monitor-frame">{camera.sourceType === "laptop_camera" ? <video ref={video} autoPlay muted playsInline /> : sourceUrl ? <video ref={video} src={sourceUrl} autoPlay muted loop playsInline /> : <div>Source will load after the monitoring lease is claimed.</div>}{observation && <>{observation.people.map((person, index) => <span className="person" key={`person-${index}`} style={boxStyle(person.bbox, observation.image)}>Person · {(person.confidence * 100).toFixed(0)}%</span>)}{observation.bins.map((bin) => <span className={`bin ${bin.state}`} key={bin.binId} style={boxStyle(bin.bbox, observation.image)}>{bin.binId} · {bin.state} · {(bin.confidence * 100).toFixed(0)}%</span>)}{observation.issues.map((issue, index) => { const box = issueBox(issue); return box && <span className={`issue ${issue.issueType}`} key={`${issue.issueType}-${index}`} style={boxStyle(box, observation.image)}>{issue.issueType.replaceAll("_", " ")} · {(issue.confidence * 100).toFixed(0)}%</span>; })}</>}</div>;
  return embedded ? <div className="current-camera-monitor embedded">{frame}{controls}{message && <p>{message}</p>}</div> : <section className="current-camera-monitor">{controls}{frame}{message && <p>{message}</p>}</section>;
}
