import { useMemo, useState, type FormEvent } from "react";
import { SiteMapViewer } from "../../components/SiteMapViewer";
import type { Cleaner } from "../../services/cleanerAPI";
import type { Zone } from "../../services/locationAPI";
import type { CreateV2CleanerInput, V2Cleaner, V2OperationsReadModel, V2Point, V2WeeklySchedule, V2WorkOrder } from "../../services/v2/operations";
import { nearestZoneForStation, type NearestZone } from "../../services/v2/stationProximity";
import type { CreateV2RegularSupervisorInput, V2SupervisorListItem, V2SupervisorManagementItem } from "../../services/v2/supervisors";
import { initialCleanerStation } from "./cleanerStationDraft";
import { SupervisorManagementPanel } from "./SupervisorManagementPanel";
import "./team-cleaner-wizard.css";
import "./team-cleaner-review.css";
import "./team-cleaner-v2.css";
import "./team-cleaner-modal-shell.css";

type RosterDay = { key: keyof V2WeeklySchedule; day: string; onDuty: boolean; start: string; end: string };
type TeamCleaner = Cleaner & { v2: V2Cleaner; station: V2Point | null; nearestZone: NearestZone | null; scheduleSummary: string };
type Draft = { staffCode: string; fullName: string; phone: string; email: string; password: string; station: V2Point | null };
type CompleteDraft = Omit<Draft, "station"> & { station: V2Point };
type TeamSiteMap = V2OperationsReadModel["siteMap"];

const weekdays: Array<[keyof V2WeeklySchedule, string]> = [["mon", "Monday"], ["tue", "Tuesday"], ["wed", "Wednesday"], ["thu", "Thursday"], ["fri", "Friday"], ["sat", "Saturday"], ["sun", "Sunday"]];
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
const time = (minute: number) => `${String(Math.floor(minute / 60)).padStart(2, "0")}:${String(minute % 60).padStart(2, "0")}`;
const minutes = (value: string) => { const [hour, minute] = value.split(":").map(Number); return hour * 60 + minute; };
const rosterFor = (schedule: V2WeeklySchedule): RosterDay[] => weekdays.map(([key, day]) => { const range = schedule[key]; return { key, day, onDuty: Boolean(range), start: range ? time(range.startMinute) : "09:00", end: range ? time(range.endMinute) : "18:00" }; });
const scheduleFor = (roster: RosterDay[]): V2WeeklySchedule => Object.fromEntries(roster.map((item) => [item.key, item.onDuty ? { startMinute: minutes(item.start), endMinute: minutes(item.end) } : null])) as V2WeeklySchedule;
const scheduleSummary = (schedule: V2WeeklySchedule) => { const activeDays = Object.values(schedule).filter(Boolean); return !activeDays.length ? "No regular schedule" : activeDays.length === 7 && activeDays.every((range) => range!.startMinute === range!.endMinute) ? "Every day · all day" : `${activeDays.length} scheduled day${activeDays.length === 1 ? "" : "s"}`; };
const nearestLabel = (nearest: NearestZone | null) => nearest ? `${nearest.name} · ${nearest.distanceMeters.toFixed(nearest.distanceMeters < 10 ? 1 : 0)} m` : "No active Zones";
const availabilityReason = (cleaner: V2Cleaner) => {
  if (cleaner.availability.available) return "Available for assignment";
  const reason = cleaner.availability.reasons[0];
  return ({ site_inactive: "Site is inactive", account_inactive: "Sign-in account is inactive", cleaner_inactive: "Cleaner profile is inactive", availability_override: "Supervisor marked unavailable", active_work_order: "Busy", invalid_station_point: "Station Point is not configured", outside_schedule: "Unavailable" } as Record<string, string>)[reason] ?? "Unavailable for assignment";
};
const availabilityStatusClass = (cleaner: V2Cleaner) => cleaner.availability.available ? "active" : cleaner.availability.reasons.includes("active_work_order") ? "busy" : "idle";
const workLabel = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const displayDate = (value?: string | null) => value ? new Date(value).toLocaleString([], { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }) : "Not recorded";

function StationMap({ point, siteMap, onChange }: { point: V2Point | null; siteMap: TeamSiteMap; onChange?: (point: V2Point) => void }) {
  const zones = siteMap.zones.map((zone) => ({ id: zone.zoneId, name: zone.zoneNameSnapshot, polygon: zone.polygon }));
  const backgroundContentUrl = siteMap.background?.contentUrl ?? (siteMap.revision.backgroundMediaId ? `/api/media/${encodeURIComponent(siteMap.revision.backgroundMediaId)}/content` : null);
  return <div className={`team-station-map shared ${onChange ? "interactive" : "readonly"}`}>
    <SiteMapViewer compact fitBoundary boundary={siteMap.revision} gridSizeMeters={siteMap.revision.gridSizeMeters} background={siteMap.background ?? null} backgroundContentUrl={backgroundContentUrl} backgroundTransform={siteMap.revision.backgroundTransform ?? null} zones={zones} pointMarker={point ? { point, label: "Station Point", tone: "station" } : null} onPlacePoint={onChange} />
    <p>{onChange ? point ? "Station Point selected. Click elsewhere on the map to move it." : "No Station Point selected. Zoom or pan, then click the map to place it." : "Exact saved Cleaner Station Point"}</p>
  </div>;
}

function CleanerModal({ cleaner, siteMap, nextNumber, onClose, onSave }: { cleaner?: TeamCleaner; siteMap: TeamSiteMap; nextNumber: number; onClose: () => void; onSave: (draft: CompleteDraft, schedule: V2WeeklySchedule) => Promise<void> }) {
  const [step, setStep] = useState(1); const [furthestStep, setFurthestStep] = useState(1); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [draft, setDraft] = useState<Draft>(() => cleaner ? { staffCode: cleaner.staffCode, fullName: cleaner.fullName, phone: cleaner.phone, email: "", password: "", station: initialCleanerStation(cleaner.station) } : { staffCode: `CLN-${String(nextNumber).padStart(3, "0")}`, fullName: "", phone: "", email: "", password: "", station: initialCleanerStation() });
  const [roster, setRoster] = useState<RosterDay[]>(() => rosterFor(cleaner ? cleaner.v2.weeklySchedule as V2WeeklySchedule : { mon: { startMinute: 540, endMinute: 1080 }, tue: { startMinute: 540, endMinute: 1080 }, wed: { startMinute: 540, endMinute: 1080 }, thu: { startMinute: 540, endMinute: 1080 }, fri: { startMinute: 540, endMinute: 1080 }, sat: null, sun: null }));
  const nearest = draft.station ? nearestZoneForStation(draft.station, siteMap.zones) : null;
  const setDraftField = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const advance = () => { if (step === 1 && (!draft.fullName.trim() || !draft.phone.trim() || (!cleaner && (!draft.email.trim() || draft.password.length < 8)))) { setMessage(cleaner ? "Add the Cleaner name and contact number before continuing." : "Add the Cleaner name, contact, email, and a password of at least 8 characters."); return; } if (step === 2 && !draft.station) { setMessage("Click the Site Map to choose this Cleaner's Station Point before continuing."); return; } const nextStep = Math.min(4, step + 1); setMessage(""); setStep(nextStep); setFurthestStep((current) => Math.max(current, nextStep)); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (step < 4) return advance(); if (!draft.station) { setMessage("Choose a Station Point before creating this Cleaner."); setStep(2); return; } setSaving(true); setMessage(""); try { await onSave({ ...draft, station: draft.station, fullName: draft.fullName.trim(), phone: draft.phone.trim(), email: draft.email.trim() }, scheduleFor(roster)); } catch (error) { setMessage(error instanceof Error ? error.message : "The Cleaner could not be saved."); } finally { setSaving(false); } };
  return <div className="team-modal-scrim" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onClose(); }}><form className="team-cleaner-modal team-cleaner-wizard" onSubmit={(event) => { void submit(event); }}><header><div><span>{cleaner ? "CLEANER PROFILE" : "NEW CLEANER"}</span><h2>{cleaner ? "Edit Cleaner" : "Create Cleaner"}</h2></div><button type="button" onClick={onClose} disabled={saving} aria-label="Close Cleaner form">×</button></header><ol className="team-wizard-steps" aria-label="Cleaner setup steps">{[["Cleaner details", cleaner ? "Profile and contact" : "Profile and sign-in"], ["Station point", draft.station ? nearestLabel(nearest) : "Not selected"], ["Duty roster", "Set weekly working time"], ["Review & confirm", "Save this Cleaner"]].map(([label, hint], index) => { const number = index + 1; const unlocked = number <= furthestStep; return <li className={step === number ? "active" : number < furthestStep ? "complete" : ""} key={label}><button type="button" onClick={() => { if (!unlocked || saving) return; setMessage(""); setStep(number); }} disabled={!unlocked || saving} aria-current={step === number ? "step" : undefined}><b>{number < furthestStep ? "✓" : String(number).padStart(2, "0")}</b><span>{label}<small>{hint}</small></span></button></li>; })}</ol><main className="team-wizard-content">
    {step === 1 && <section className="team-wizard-panel team-wizard-details"><span>Cleaner details</span><h3>Start with the person.</h3><p>{cleaner ? "Update the Cleaner profile. Their existing sign-in email stays unchanged." : "Create the Cleaner profile and their mobile web sign-in credentials."}</p><div className="team-wizard-field-grid"><label>Full name<input value={draft.fullName} onChange={(event) => setDraftField("fullName", event.target.value)} placeholder="Cleaner name" required autoFocus /></label><label>Staff ID<input value={draft.staffCode} onChange={(event) => setDraftField("staffCode", event.target.value.toUpperCase())} required disabled={Boolean(cleaner)} /></label><label>Contact number<input value={draft.phone} onChange={(event) => setDraftField("phone", event.target.value)} placeholder="+60 12-345 6789" required /></label>{!cleaner && <><label>Email address<input type="email" value={draft.email} onChange={(event) => setDraftField("email", event.target.value)} placeholder="cleaner@example.com" required /></label><label>Password<input type="password" minLength={8} value={draft.password} onChange={(event) => setDraftField("password", event.target.value)} placeholder="At least 8 characters" required /></label></>}</div></section>}
    {step === 2 && <section className="team-wizard-panel team-wizard-location"><header><div><span>Station point</span><h3>Pin the default working location.</h3><p>Choose a point on the Site Map.</p></div><div className={`team-station-zone-readout ${draft.station ? "" : "empty"}`}><span>{draft.station ? "NEAREST ZONE" : "STATION POINT"}</span><strong>{draft.station ? nearestLabel(nearest) : "Not selected"}</strong><small>{draft.station ? `X ${draft.station.xMeters} m · Y ${draft.station.yMeters} m` : "Click the map to place"}</small></div></header><StationMap point={draft.station} siteMap={siteMap} onChange={(point) => setDraftField("station", point)} /></section>}
    {step === 3 && <section className="team-wizard-panel team-wizard-roster"><header><div><span>Duty roster</span><h3>Set weekly working time.</h3><p>Only on-duty Cleaners can receive Work Orders.</p></div><button type="button" disabled={saving} onClick={() => setRoster((items) => items.map((item, index) => ({ ...item, onDuty: index < 5, start: "09:00", end: "18:00" })))}>Copy Monday to weekdays</button></header><div className="team-roster-editor"><div className="team-roster-editor-label"><span>DAY</span><span>ON DUTY</span><span>START</span><span>END</span></div>{roster.map((item, index) => <div className="team-roster-editor-row" key={item.key}><strong>{item.day}</strong><label className="team-duty-toggle"><input type="checkbox" checked={item.onDuty} onChange={(event) => setRoster((items) => items.map((current, currentIndex) => currentIndex === index ? { ...current, onDuty: event.target.checked } : current))} /><i /><span>{item.onDuty ? "On duty" : "Off duty"}</span></label><input type="time" value={item.start} disabled={!item.onDuty} onChange={(event) => setRoster((items) => items.map((current, currentIndex) => currentIndex === index ? { ...current, start: event.target.value } : current))} /><input type="time" value={item.end} disabled={!item.onDuty} onChange={(event) => setRoster((items) => items.map((current, currentIndex) => currentIndex === index ? { ...current, end: event.target.value } : current))} /></div>)}</div></section>}
    {step === 4 && <section className="team-wizard-panel team-wizard-review"><header><span>Review and confirm</span><h3>Check the setup before saving.</h3></header><div className="team-review-card"><header><h4>Cleaner details</h4><button type="button" onClick={() => setStep(1)}>Edit</button></header><dl><div><dt>Name</dt><dd>{draft.fullName || "—"}</dd></div><div><dt>Staff ID</dt><dd>{draft.staffCode}</dd></div><div><dt>Contact</dt><dd>{draft.phone || "—"}</dd></div>{!cleaner && <div><dt>Sign-in email</dt><dd>{draft.email || "—"}</dd></div>}</dl></div><div className="team-review-card team-review-station"><header><h4>Station point</h4><button type="button" onClick={() => setStep(2)}>Edit</button></header><div className="team-review-map"><StationMap point={draft.station} siteMap={siteMap} /></div><p><b>{draft.station ? nearestLabel(nearest) : "Not selected"}</b><span>{draft.station ? `X ${draft.station.xMeters} m · Y ${draft.station.yMeters} m` : "Return to Station point and click the map"}</span></p></div><div className="team-review-card"><header><h4>Weekly duty roster</h4><button type="button" onClick={() => setStep(3)}>Edit</button></header><div className="team-review-roster team-review-roster-table">{roster.map((item) => <p key={item.key}><b>{item.day}</b><span>{item.onDuty ? "On duty" : "Off duty"}</span><span>{item.onDuty ? item.start : "—"}</span><i>—</i><span>{item.onDuty ? item.end : "—"}</span></p>)}</div></div></section>}
  </main>{message && <p className="team-cleaner-error" role="alert">{message}</p>}<footer><p>{cleaner ? "Saving updates the profile, duty roster, and Station Point in the active V2 Site Map." : "Creating a Cleaner provisions their sign-in account and publishes their Station Point in the active V2 Site Map."}</p><div><button type="button" onClick={onClose} disabled={saving}>Cancel</button>{step > 1 && <button type="button" onClick={() => { setMessage(""); setStep((current) => current - 1); }} disabled={saving}>Back</button>}<button type="submit" disabled={saving}>{step === 4 ? saving ? "Saving…" : cleaner ? "Save Cleaner" : "Create Cleaner" : "Continue"}</button></div></footer></form></div>;
}

function CleanerViewModal({ cleaner, siteMap, work, onClose, onEdit, onAvailability, readOnly = false }: { cleaner: TeamCleaner; siteMap: TeamSiteMap; work?: V2WorkOrder; onClose: () => void; onEdit: () => void; onAvailability: (availabilityOverride: "none" | "unavailable") => Promise<void>; readOnly?: boolean }) {
  const schedule = rosterFor(cleaner.v2.weeklySchedule as V2WeeklySchedule);
  const station = cleaner.v2.stationPoint;
  const overridden = cleaner.v2.availabilityOverride === "unavailable" || cleaner.v2.availability.reasons.includes("availability_override");
  const canOverride = cleaner.v2.status === "active" && !cleaner.v2.activeWorkOrderId && (cleaner.v2.availability.available || overridden);
  const [changingAvailability, setChangingAvailability] = useState(false);
  const [message, setMessage] = useState("");
  const changeAvailability = async () => { setChangingAvailability(true); setMessage(""); try { await onAvailability(overridden ? "none" : "unavailable"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Cleaner availability could not be changed."); } finally { setChangingAvailability(false); } };
  const openWork = () => { if (!work) return; if (work.cameraId) location.hash = `/cameras?cameraId=${encodeURIComponent(work.cameraId)}&zoneId=${encodeURIComponent(work.zoneId ?? "all")}&workId=${encodeURIComponent(work.id)}&from=team`; else location.hash = `/history?workId=${encodeURIComponent(work.id)}`; };

  return <div className="team-modal-scrim" onMouseDown={(event) => { if (event.target === event.currentTarget && !changingAvailability) onClose(); }}><section className="team-cleaner-modal team-cleaner-view" role="dialog" aria-modal="true" aria-labelledby="cleaner-view-title">
    <header><div className="team-view-identity"><i>{initials(cleaner.fullName)}</i><div><span>CLEANER PROFILE</span><h2 id="cleaner-view-title">{cleaner.fullName}</h2><p>{cleaner.staffCode} · Cleaner</p></div></div><div className="team-view-header-actions"><b className={`team-status ${cleaner.v2.availability.available ? "active" : "inactive"}`}>{cleaner.v2.availability.available ? "Available" : "Unavailable"}</b><button type="button" onClick={onClose} disabled={changingAvailability} aria-label="Close Cleaner profile">×</button></div></header>
    <main className="team-view-body">
      <section className="team-view-station"><header><div><span>STATION POINT</span><h3>{station ? cleaner.nearestZone?.name ?? "Site Station Point" : "Not configured"}</h3></div></header>{station ? <div className="team-view-map-wrap"><StationMap point={station} siteMap={siteMap} /><div className="team-station-zone-readout team-view-map-readout"><span>NEAREST ZONE</span><strong>{nearestLabel(cleaner.nearestZone)}</strong><small>X {station.xMeters} m · Y {station.yMeters} m</small></div></div> : <div className="team-view-empty"><strong>No Station Point</strong><p>Edit this Cleaner to set their default assignment starting point.</p></div>}</section>
      <aside className="team-view-summary">
        <section><span>CLEANER DETAILS</span><dl><div><dt>Full name</dt><dd>{cleaner.fullName}</dd></div><div><dt>Staff ID</dt><dd>{cleaner.staffCode}</dd></div><div><dt>Contact number</dt><dd>{cleaner.phone}</dd></div><div><dt>Account status</dt><dd>{cleaner.v2.status}</dd></div><div><dt>Last updated</dt><dd>{displayDate(cleaner.v2.updatedAt)}</dd></div></dl>{cleaner.v2.notes && <p className="team-view-notes">{cleaner.v2.notes}</p>}</section>
        <section className="team-view-availability"><span>CURRENT AVAILABILITY</span><strong className={cleaner.v2.availability.available ? "available" : "unavailable"}>{cleaner.v2.availability.available ? "Available" : "Unavailable"}</strong><p>{availabilityReason(cleaner.v2)}</p></section>
        <section className="team-view-work"><span>CURRENT WORK</span>{work ? <><h3>{work.title || workLabel(work.issueType)}</h3><dl><div><dt>Status</dt><dd>{workLabel(work.status)}</dd></div><div><dt>Severity</dt><dd>{work.severity}</dd></div><div><dt>Target</dt><dd>{work.target.zoneNameSnapshot}</dd></div><div><dt>Assigned</dt><dd>{displayDate(work.assignedAt ?? work.createdAt)}</dd></div></dl><button type="button" onClick={openWork}>View Work</button></> : <div className="team-view-no-work"><strong>No active Work Order</strong><p>This Cleaner has no assigned response.</p></div>}</section>
      </aside>
      <section className="team-view-schedule"><header><div><span>WEEKLY WORKING SCHEDULE</span><h3>{cleaner.scheduleSummary}</h3></div><small>{cleaner.v2.scheduleTimeZone ?? "Site local time"}</small></header><div>{schedule.map((item) => <p key={item.key}><b>{item.day}</b><span>{item.onDuty ? "On duty" : "Off duty"}</span><time>{item.onDuty ? item.start === item.end ? "All day" : `${item.start} – ${item.end}` : "—"}</time></p>)}</div></section>
    </main>
    {message && <p className="team-cleaner-error" role="alert">{message}</p>}
    <footer><p>{readOnly ? "Cleaner profile, Station Point, Work, and schedule." : "Profile edits open the existing four-page Cleaner workflow. Availability override is a separate daily operation."}</p><div><button type="button" onClick={onClose} disabled={changingAvailability}>Close</button>{!readOnly && canOverride && <button type="button" className="team-view-availability-action" onClick={() => void changeAvailability()} disabled={changingAvailability}>{changingAvailability ? "Updating…" : overridden ? "Return to schedule" : "Set unavailable"}</button>}{!readOnly && <button type="button" className="team-view-edit" onClick={onEdit} disabled={changingAvailability}>Edit Cleaner</button>}</div></footer>
  </section></div>;
}

export function TeamManagementPage({ viewer, staff, zones, v2Cleaners, cleanerTotal = v2Cleaners.length, cleanerHasMore = false, onLoadMoreCleaners, workOrders, siteMap, supervisors, supervisorTotal = supervisors.length, supervisorHasMore = false, onLoadMoreSupervisors, supervisorsLoading, supervisorsError, onRetrySupervisors, onCreateSupervisor, onUpdateSupervisor, onCreate, onUpdate, onMoveStation, onAvailabilityOverride, readOnly = false }: { viewer: { uid: string; authority: "root" | "regular" }; staff: Cleaner[]; zones: Zone[]; v2Cleaners: V2Cleaner[]; cleanerTotal?: number; cleanerHasMore?: boolean; onLoadMoreCleaners?: () => Promise<void>; workOrders: V2WorkOrder[]; siteMap: TeamSiteMap; supervisors: V2SupervisorListItem[]; supervisorTotal?: number; supervisorHasMore?: boolean; onLoadMoreSupervisors?: () => Promise<void>; supervisorsLoading: boolean; supervisorsError?: string; onRetrySupervisors: () => void; onCreateSupervisor: (input: CreateV2RegularSupervisorInput) => Promise<void>; onUpdateSupervisor: (supervisor: V2SupervisorManagementItem, input: { fullName?: string; phone?: string | null; status?: "active" | "inactive" }) => Promise<void>; onCreate: (input: CreateV2CleanerInput) => Promise<void>; onUpdate: (cleaner: V2Cleaner, input: { fullName: string; phone: string; weeklySchedule: V2WeeklySchedule }) => Promise<void>; onMoveStation: (cleaner: V2Cleaner, point: V2Point) => Promise<void>; onAvailabilityOverride: (cleaner: V2Cleaner, availabilityOverride: "none" | "unavailable") => Promise<void>; readOnly?: boolean }) {
  const [section, setSection] = useState<"cleaners" | "supervisors">("cleaners");
  const [supervisorCreateRequest, setSupervisorCreateRequest] = useState(0);
  const [status, setStatus] = useState<"all" | "active" | "inactive">("all"); const [zoneFilter, setZoneFilter] = useState("all"); const [query, setQuery] = useState(""); const [viewingId, setViewingId] = useState(""); const [editingId, setEditingId] = useState(""); const [creating, setCreating] = useState(false);
  const roster = useMemo<TeamCleaner[]>(() => v2Cleaners.map((cleaner) => ({ id: cleaner.id, staffCode: cleaner.staffCode, fullName: cleaner.fullName, phone: cleaner.phone, assignedSiteId: "", assignedZoneId: "", assignedZoneName: "", status: cleaner.status, notes: cleaner.notes, createdAt: null, updatedAt: null, deactivatedAt: null, v2: cleaner, station: cleaner.stationPoint, nearestZone: cleaner.stationPoint ? nearestZoneForStation(cleaner.stationPoint, siteMap.zones) : null, scheduleSummary: scheduleSummary(cleaner.weeklySchedule as V2WeeklySchedule) })), [siteMap.zones, v2Cleaners]);
  const viewing = roster.find((cleaner) => cleaner.id === viewingId); const editing = roster.find((cleaner) => cleaner.id === editingId);
  const available = roster.filter((cleaner) => cleaner.v2.availability.available).length; const shown = roster.filter((cleaner) => (status === "all" || status === "active" && cleaner.v2.availability.available || status === "inactive" && !cleaner.v2.availability.available) && (zoneFilter === "all" || cleaner.nearestZone?.id === zoneFilter) && `${cleaner.fullName} ${cleaner.staffCode}`.toLowerCase().includes(query.toLowerCase())); const nextNumber = Math.max(0, ...roster.map((cleaner) => Number(cleaner.staffCode.match(/\d+$/)?.[0] ?? 0))) + 1;
  const save = async (draft: CompleteDraft, weeklySchedule: V2WeeklySchedule) => { if (editing) { const cleanerId = editing.id; await onUpdate(editing.v2, { fullName: draft.fullName, phone: draft.phone, weeklySchedule }); await onMoveStation(editing.v2, draft.station); setEditingId(""); setViewingId(cleanerId); } else { await onCreate({ staffCode: draft.staffCode, fullName: draft.fullName, phone: draft.phone, email: draft.email, password: draft.password, weeklySchedule, stationPoint: draft.station }); setCreating(false); } };
  return <section className="team-management-page">
    <header className="team-page-heading"><div><span>TEAM</span><h1>Keep the site team ready.</h1><p>Cleaner coverage and Supervisor access for the active Site.</p></div>{!readOnly && (section === "cleaners" ? <button type="button" onClick={() => setCreating(true)}><i>+</i>Create Cleaner</button> : viewer.authority === "root" ? <button type="button" onClick={() => setSupervisorCreateRequest((value) => value + 1)}><i>+</i>Create Regular Supervisor</button> : null)}</header>
    <nav className="team-section-tabs" aria-label="Team directory sections"><button type="button" className={section === "cleaners" ? "active" : ""} aria-current={section === "cleaners" ? "page" : undefined} onClick={() => setSection("cleaners")}><span>Cleaners</span><b>{cleanerTotal}</b><small>Coverage, Work and schedules</small></button><button type="button" className={section === "supervisors" ? "active" : ""} aria-current={section === "supervisors" ? "page" : undefined} onClick={() => setSection("supervisors")}><span>Supervisors</span><b>{supervisorTotal}</b><small>Site access and authority</small></button></nav>
    {section === "cleaners" ? <><section className="team-metric-grid"><article><span>REGISTERED CLEANERS</span><strong>{roster.length}</strong><small>Across the active Site</small></article><article><span>AVAILABLE NOW</span><strong>{available}</strong><small>Ready for assignment</small></article><article><span>UNAVAILABLE</span><strong>{roster.length - available}</strong><small>Outside schedule, overridden, busy, or inactive</small></article></section><section className="team-filters"><div role="group" aria-label="Filter Cleaners by availability"><button className={status === "all" ? "active" : ""} onClick={() => setStatus("all")}>All <b>{roster.length}</b></button><button className={status === "active" ? "active" : ""} onClick={() => setStatus("active")}>Available <b>{available}</b></button><button className={status === "inactive" ? "active" : ""} onClick={() => setStatus("inactive")}>Unavailable <b>{roster.length - available}</b></button></div><label>NEAREST ZONE<select value={zoneFilter} onChange={(event) => setZoneFilter(event.target.value)}><option value="all">All Zones</option>{zones.map((zone) => <option value={zone.id} key={zone.id}>{zone.name}</option>)}</select></label><label className="team-search">FIND CLEANER<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name or staff ID" /></label></section><section className="team-roster"><header><div><span>REGISTERED CLEANERS</span><h2>Cleaner roster</h2></div><p>Click a Cleaner to view their profile, Station Point, availability, current Work, and weekly schedule.</p></header><div className="team-roster-table"><div className="team-roster-row team-roster-label"><span>Cleaner</span><span>Nearest zone</span><span>Station Point</span><span>Schedule</span><span>Availability</span></div>{shown.map((cleaner) => <button className="team-roster-row" type="button" key={cleaner.id} onClick={() => setViewingId(cleaner.id)}><span className="team-person"><i>{initials(cleaner.fullName)}</i><b>{cleaner.fullName}<small>{cleaner.staffCode} · {cleaner.phone}</small></b></span><span>{cleaner.nearestZone ? nearestLabel(cleaner.nearestZone) : "Not configured"}</span><span className="team-station-cell">{cleaner.station ? <><i /> X {cleaner.station.xMeters.toFixed(0)} · Y {cleaner.station.yMeters.toFixed(0)}</> : "Not configured"}</span><span>{cleaner.scheduleSummary}</span><span><b className={`team-status ${availabilityStatusClass(cleaner.v2)}`}>{cleaner.v2.availability.available ? "Available" : availabilityReason(cleaner.v2)}</b></span></button>)}{!shown.length && <p className="team-empty">No registered Cleaners match this filter.</p>}</div></section></> : <SupervisorManagementPanel readOnly={readOnly} viewer={viewer} supervisors={supervisors} loading={supervisorsLoading} error={supervisorsError} createRequest={supervisorCreateRequest} onRetry={onRetrySupervisors} onCreate={onCreateSupervisor} onUpdate={onUpdateSupervisor} />}
    {section === "cleaners" && cleanerHasMore && <button className="operations-load-more" type="button" onClick={() => void onLoadMoreCleaners?.()}>Load more · {roster.length} of {cleanerTotal}</button>}{section === "supervisors" && supervisorHasMore && <button className="operations-load-more" type="button" onClick={() => void onLoadMoreSupervisors?.()}>Load more · {supervisors.length} of {supervisorTotal}</button>}
    {!readOnly && creating && <CleanerModal siteMap={siteMap} nextNumber={nextNumber} onClose={() => setCreating(false)} onSave={save} />}{viewing && <CleanerViewModal readOnly={readOnly} cleaner={viewing} siteMap={siteMap} work={workOrders.find((work) => work.id === viewing.v2.activeWorkOrderId)} onClose={() => setViewingId("")} onEdit={() => { setViewingId(""); setEditingId(viewing.id); }} onAvailability={(availabilityOverride) => onAvailabilityOverride(viewing.v2, availabilityOverride)} />}{!readOnly && editing && <CleanerModal cleaner={editing} siteMap={siteMap} nextNumber={nextNumber} onClose={() => { setEditingId(""); setViewingId(editing.id); }} onSave={save} />}
  </section>;
}
