import { useEffect, useMemo, useRef, useState } from "react";
import { api, authorizedBlob, firebaseLogin, type ApiSettings } from "./api";
import { CameraRuntimeSandbox } from "./CameraRuntimeSandbox";

type Point = { x: number; y: number };
type MapPoint = { xMeters: number; yMeters: number };
type Stage = "connect" | "register" | "monitor" | "alerts";
type Log = { at: string; level: "ok" | "warn" | "info"; message: string };

const json = (value: unknown): RequestInit => ({ method: "POST", body: JSON.stringify(value) });
const put = (value: unknown): RequestInit => ({ method: "PUT", body: JSON.stringify(value) });
const now = () => new Date().toLocaleTimeString([], { hour12: false });

function Scope({ label, value }: { label: string; value: string }) { return <div className="scope"><span>{label}</span><strong>{value || "—"}</strong></div>; }
function Button(props: React.ButtonHTMLAttributes<HTMLButtonElement> & { tone?: "primary" | "warning" }) { const { tone, className = "", ...rest } = props; return <button {...rest} className={`${tone === "primary" ? "primary" : tone === "warning" ? "warning" : ""} ${className}`.trim()} />; }

function SiteMap({ map, selected, onSelect }: { map: any; selected: MapPoint | null; onSelect: (point: MapPoint) => void }) {
  const revision = map?.revision ?? {}; const width = Number(revision.widthMeters ?? 100); const height = Number(revision.heightMeters ?? 100); const zones = map?.zones ?? [];
  return <div className="map-shell"><svg className="site-map" viewBox={`0 0 ${width} ${height}`} onClick={(event) => { const rect = event.currentTarget.getBoundingClientRect(); onSelect({ xMeters: ((event.clientX - rect.left) / rect.width) * width, yMeters: ((event.clientY - rect.top) / rect.height) * height }); }} role="img" aria-label="Site Map. Click inside a Zone to place the Camera.">
    <defs><pattern id="grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M 5 0 L 0 0 0 5" fill="none" stroke="currentColor" strokeWidth=".18" /></pattern></defs>
    <rect width={width} height={height} className="map-grid" />
    {zones.map((zone: any) => <g key={zone.id}><polygon points={(zone.polygon ?? []).map((point: any) => `${point.xMeters},${point.yMeters}`).join(" ")} /><text x={zone.centroid?.xMeters ?? zone.polygon?.[0]?.xMeters ?? 2} y={zone.centroid?.yMeters ?? zone.polygon?.[0]?.yMeters ?? 4}>{zone.zoneNameSnapshot ?? zone.id}</text></g>)}
    {selected && <g className="probe"><circle cx={selected.xMeters} cy={selected.yMeters} r="1.6" /><path d={`M ${selected.xMeters - 3} ${selected.yMeters} H ${selected.xMeters + 3} M ${selected.xMeters} ${selected.yMeters - 3} V ${selected.yMeters + 3}`} /></g>}
  </svg><div className="axis"><span>0 m</span><span>{width} × {height} m</span></div></div>;
}

function RegistrationPlot({ imageUrl, floor, bins, currentBin, mode, onPoint, onMode, onLockBin, onReset }: { imageUrl: string; floor: Point[]; bins: Array<{ binId: string; displayName: string; binType: string; binPolygon: Point[] }>; currentBin: Point[]; mode: "floor" | "bin"; onPoint: (point: Point) => void; onMode: (mode: "floor" | "bin") => void; onLockBin: () => void; onReset: () => void }) {
  const polygon = (points: Point[]) => points.map((point) => `${point.x},${point.y}`).join(" ");
  return <div><div className="plot-tools"><Button className={mode === "floor" ? "active" : ""} onClick={() => onMode("floor")}>Plot floor</Button><Button className={mode === "bin" ? "active" : ""} onClick={() => onMode("bin")}>Plot bin</Button><Button onClick={onLockBin} disabled={currentBin.length < 3}>Lock bin</Button><Button onClick={onReset}>Reset geometry</Button></div>
    <div className="registration-plot"><img src={imageUrl} alt="Camera reference used for plotting" /><svg viewBox="0 0 1 1" preserveAspectRatio="none" onClick={(event) => { const rect = event.currentTarget.getBoundingClientRect(); onPoint({ x: (event.clientX - rect.left) / rect.width, y: (event.clientY - rect.top) / rect.height }); }}>
      {floor.length >= 2 && <polyline points={polygon(floor)} className="floor-trace" />}{floor.map((point, index) => <circle key={`f${index}`} cx={point.x} cy={point.y} r=".007" className="floor-node" />)}
      {bins.map((bin) => <polygon key={bin.binId} points={polygon(bin.binPolygon)} className="bin-trace" />)}{currentBin.length >= 2 && <polyline points={polygon(currentBin)} className="bin-trace current" />}{currentBin.map((point, index) => <circle key={`b${index}`} cx={point.x} cy={point.y} r=".007" className="bin-node" />)}
    </svg></div>
  </div>;
}

export function App() {
  const [stage, setStage] = useState<Stage>("connect"); const [baseUrl, setBaseUrl] = useState(localStorage.getItem("sandboxBaseUrl") ?? "http://127.0.0.1:3000"); const [apiKey, setApiKey] = useState(localStorage.getItem("sandboxApiKey") ?? ""); const [email, setEmail] = useState(localStorage.getItem("sandboxEmail") ?? "root@sunway-test.com"); const [password, setPassword] = useState(""); const [token, setToken] = useState(sessionStorage.getItem("sandboxToken") ?? "");
  const settings = useMemo<ApiSettings>(() => ({ baseUrl, apiKey, email, token }), [baseUrl, apiKey, email, token]); const [logs, setLogs] = useState<Log[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [profile, setProfile] = useState<any>(null); const [map, setMap] = useState<any>(null); const [cameras, setCameras] = useState<any[]>([]); const [alerts, setAlerts] = useState<any[]>([]);
  const log = (message: string, level: Log["level"] = "info") => setLogs((items) => [{ at: now(), level, message }, ...items].slice(0, 80)); const run = async <T,>(label: string, action: () => Promise<T>) => { setBusy(true); setError(""); try { const result = await action(); log(label, "ok"); return result; } catch (cause) { const message = cause instanceof Error ? cause.message : String(cause); setError(message); log(`${label}: ${message}`, "warn"); throw cause; } finally { setBusy(false); } };
  const refreshMap = async () => { const response = await api<any>(settings, "/api/site-map"); setMap(response.map); return response.map; }; const refreshCameras = async () => { const response = await api<any>(settings, "/api/camera-creation/cameras"); setCameras(response.cameras); return response.cameras; }; const refreshAlerts = async () => { const response = await api<any>(settings, "/api/alerts"); setAlerts(response.alerts); return response.alerts; };
  const connect = async () => run("Authenticated against Firebase and Node", async () => { const idToken = await firebaseLogin(apiKey, email, password); sessionStorage.setItem("sandboxToken", idToken); localStorage.setItem("sandboxBaseUrl", baseUrl); localStorage.setItem("sandboxApiKey", apiKey); localStorage.setItem("sandboxEmail", email); setToken(idToken); const authenticated = { ...settings, token: idToken }; const me = await api<any>(authenticated, "/api/me"); if (me.role !== "supervisor" || me.supervisor?.authority !== "root") throw new Error("The sandbox requires the Sunway Root Supervisor account."); setProfile(me.supervisor); const mapResponse = await api<any>(authenticated, "/api/site-map"); setMap(mapResponse.map); const cameraResponse = await api<any>(authenticated, "/api/camera-creation/cameras"); setCameras(cameraResponse.cameras); setStage("register"); });

  const [placement, setPlacement] = useState<MapPoint | null>(null); const [cameraName, setCameraName] = useState("Sandbox Camera"); const [sourceType, setSourceType] = useState<"laptop_camera" | "looped_video">("laptop_camera"); const [draft, setDraft] = useState<any>(null); const [sourceFile, setSourceFile] = useState<File | null>(null); const [sourceStored, setSourceStored] = useState(false); const [referenceFile, setReferenceFile] = useState<File | null>(null); const [referenceStored, setReferenceStored] = useState(false); const [referenceUrl, setReferenceUrl] = useState(""); const [referenceSize, setReferenceSize] = useState({ width: 0, height: 0 }); const [floor, setFloor] = useState<Point[]>([]); const [bins, setBins] = useState<Array<{ binId: string; displayName: string; binType: string; binPolygon: Point[] }>>([]); const [currentBin, setCurrentBin] = useState<Point[]>([]); const [plotMode, setPlotMode] = useState<"floor" | "bin">("floor"); const referenceVideo = useRef<HTMLVideoElement>(null); const captureCanvas = useRef<HTMLCanvasElement>(null); const streamRef = useRef<MediaStream | null>(null);
  const startDraft = async () => run("Camera Draft started", async () => { if (!placement) throw new Error("Click a point inside a Site Map Zone first."); const response = await api<any>(settings, "/api/camera-creation/drafts/start", json({ kind: "create", name: cameraName, description: "Created from isolated API sandbox", sourceType, placement: { point: placement } })); setDraft(response.draft); setSourceStored(false); setReferenceStored(false); setFloor([]); setBins([]); setCurrentBin([]); return response; });
  const openWebcam = async (video = referenceVideo.current) => { streamRef.current?.getTracks().forEach((track) => track.stop()); const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: false }); streamRef.current = stream; if (video) { video.srcObject = stream; await video.play(); } log("Laptop Camera opened", "ok"); };
  const stopWebcam = () => { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; for (const video of [referenceVideo.current, monitorVideo.current]) if (video?.srcObject) { video.pause(); video.srcObject = null; } log("Webcam stopped", "info"); };
  const loadSourceFile = async (file: File) => { stopWebcam(); setSourceFile(file); setSourceStored(false); if (referenceVideo.current) { referenceVideo.current.srcObject = null; referenceVideo.current.src = URL.createObjectURL(file); referenceVideo.current.loop = true; await referenceVideo.current.play(); } };
  const storeSource = async () => { if (!draft || !sourceFile) throw new Error("Start a looped-video Draft and choose its source video."); const body = new FormData(); body.append("video", sourceFile); const response = await api<any>(settings, `/api/camera-creation/drafts/${draft.id}/source-video`, { method: "POST", body }); setSourceStored(true); return response; };
  const uploadSource = async () => run("Looped source video stored", storeSource);
  const chooseReference = (file: File) => { setReferenceFile(file); setReferenceStored(false); const url = URL.createObjectURL(file); setReferenceUrl(url); const image = new Image(); image.onload = () => setReferenceSize({ width: image.naturalWidth, height: image.naturalHeight }); image.src = url; };
  const captureReference = async () => { const video = referenceVideo.current; const canvas = captureCanvas.current; if (!video || !canvas || !video.videoWidth) throw new Error("Start the Camera preview before capturing a reference."); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext("2d")!.drawImage(video, 0, 0); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/jpeg", .9)); if (!blob) throw new Error("Reference capture failed."); chooseReference(new File([blob], "camera-reference.jpg", { type: "image/jpeg" })); log("Reference frame captured", "ok"); };
  const storeReference = async () => { if (!draft || !referenceFile) throw new Error("Capture or choose a reference image first."); const body = new FormData(); body.append("image", referenceFile); const response = await api<any>(settings, `/api/camera-creation/drafts/${draft.id}/reference`, { method: "POST", body }); setReferenceStored(true); return response; };
  const uploadReference = async () => run("Reference image stored", storeReference);
  const storeRegistration = async () => { if (!draft || floor.length < 3 || !referenceSize.width) throw new Error("Plot at least three floor points on a reference image."); return api<any>(settings, `/api/camera-creation/drafts/${draft.id}/registration`, put({ sourceWidth: referenceSize.width, sourceHeight: referenceSize.height, walkableFloorPolygon: floor, bins })); };
  const saveRegistration = async () => run("Floor and bin Registration saved", storeRegistration);
  const validateAndPublish = async () => run("Camera validated and published", async () => { if (!draft) throw new Error("No Camera Draft is active."); if (sourceType === "looped_video" && !sourceStored) { await storeSource(); log("Looped source video stored automatically", "ok"); } if (!referenceStored) { await storeReference(); log("Reference image stored automatically", "ok"); } await storeRegistration(); log("Registration stored automatically", "ok"); const validation = await api<any>(settings, `/api/camera-creation/drafts/${draft.id}/validate`, json({})); if (!validation.valid) throw new Error(`Draft is invalid: ${validation.errors.join(", ")}`); await api(settings, `/api/camera-creation/drafts/${draft.id}/publish`, json({})); stopWebcam(); await refreshMap(); await refreshCameras(); setDraft(null); setStage("monitor"); });

  const [selectedCameraId, setSelectedCameraId] = useState(""); const selectedCamera = cameras.find((camera) => camera.id === selectedCameraId) ?? cameras[0]; const monitorVideo = useRef<HTMLVideoElement>(null); const overlayCanvas = useRef<HTMLCanvasElement>(null); const samplingTimer = useRef<number | null>(null); const heartbeatTimer = useRef<number | null>(null); const [session, setSession] = useState<any>(null); const [episode, setEpisode] = useState<any>(null); const sequence = useRef(0); const [sampleResult, setSampleResult] = useState<any>(null); const [monitoring, setMonitoring] = useState(false);
  useEffect(() => { if (!selectedCameraId && cameras[0]) setSelectedCameraId(cameras[0].id); }, [cameras, selectedCameraId]);
  const prepareMonitorSource = async () => { const video = monitorVideo.current; if (!video || !selectedCamera) throw new Error("Select a Camera."); if (selectedCamera.sourceType === "laptop_camera") return openWebcam(video); const blob = await authorizedBlob(settings, selectedCamera.source.contentUrl); video.srcObject = null; video.src = URL.createObjectURL(blob); video.loop = true; await video.play(); };
  const drawOverlay = (result: any) => {
    const canvas = overlayCanvas.current; const video = monitorVideo.current; if (!canvas || !video) return;
    canvas.width = video.videoWidth || 640; canvas.height = video.videoHeight || 480;
    const context = canvas.getContext("2d")!; context.clearRect(0, 0, canvas.width, canvas.height);
    const image = result?.observation?.image ?? { width: canvas.width, height: canvas.height };
    const color = (kind: string, state?: string) => {
      if (kind === "bin" && state === "overflow") return "#ff715f";
      if (kind === "bin" && state === "full") return "#ffd166";
      if (kind === "bin" && (state === "review" || state === "unknown")) return "#b0bec8";
      if (kind === "floor_litter") return "#ffd166";
      if (kind === "floor_spill") return "#c79cff";
      return "#48f0c0";
    };
    const box = (bbox: any, label: string, accent: string) => {
      if (!bbox) return;
      const x = (bbox.x1 / image.width) * canvas.width; const y = (bbox.y1 / image.height) * canvas.height;
      const width = ((bbox.x2 - bbox.x1) / image.width) * canvas.width; const height = ((bbox.y2 - bbox.y1) / image.height) * canvas.height;
      context.strokeStyle = accent; context.lineWidth = 3; context.strokeRect(x, y, width, height);
      context.font = "700 13px ui-monospace"; const textWidth = context.measureText(label).width;
      const labelY = Math.max(0, y); context.fillStyle = accent; context.fillRect(x, labelY, textWidth + 12, 22);
      context.fillStyle = "#04110d"; context.fillText(label, x + 6, labelY + 15);
    };
    for (const bin of result?.observation?.bins ?? []) box(bin.bbox, `BIN · ${String(bin.state).toUpperCase()} ${Math.round(bin.confidence * 100)}%`, color("bin", bin.state));
    for (const person of result?.observation?.people ?? []) box(person.bbox, `PEOPLE ${Math.round(person.confidence * 100)}%`, color("person"));
    for (const issue of result?.observation?.issues ?? []) {
      if (issue.issueType === "bin_service") continue;
      box(issue.geometry?.bbox, `${issue.condition.toUpperCase()} ${Math.round(issue.confidence * 100)}%`, color(issue.issueType));
    }
  };
  const sendFrame = async (activeSession = session, activeEpisode = episode) => { const video = monitorVideo.current; const canvas = captureCanvas.current; if (!video || !canvas || !video.videoWidth || !activeSession || !activeEpisode) return; canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext("2d")!.drawImage(video, 0, 0); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/jpeg", .82)); if (!blob) return; sequence.current += 1; const body = new FormData(); body.append("frame", blob, `sample-${sequence.current}.jpg`); body.append("episodeId", activeEpisode.episodeId); body.append("sequence", String(sequence.current)); body.append("capturedAt", new Date().toISOString()); const result = await api<any>(settings, `/api/monitoring/sessions/${activeSession.sessionId}/cameras/${selectedCamera.id}/samples`, { method: "POST", headers: { "x-monitoring-token": activeSession.leaseToken }, body }); setSampleResult(result); drawOverlay(result); log(`Sample ${sequence.current}: ${result.observation.issues.length} issue signal(s)`, result.observation.issues.length ? "warn" : "ok"); };
  const beginMonitoring = async () => run("Monitoring Session and Camera Episode started", async () => { if (!selectedCamera) throw new Error("Select a Camera."); if (!selectedCamera.monitoringEnabled) { await api(settings, `/api/camera-creation/cameras/${selectedCamera.id}/monitoring`, { method: "PATCH", body: JSON.stringify({ monitoringEnabled: true, expectedRevision: selectedCamera.revision }) }); await refreshCameras(); } await prepareMonitorSource(); const claimed = await api<any>(settings, "/api/monitoring/sessions/claim", json({})); const started = await api<any>(settings, `/api/monitoring/sessions/${claimed.sessionId}/cameras/${selectedCamera.id}/start`, { ...json({}), headers: { "x-monitoring-token": claimed.leaseToken } }); setSession(claimed); setEpisode(started); sequence.current = 0; setMonitoring(true); heartbeatTimer.current = window.setInterval(() => { void api(settings, `/api/monitoring/sessions/${claimed.sessionId}/heartbeat`, { ...json({}), headers: { "x-monitoring-token": claimed.leaseToken } }).catch((cause) => log(`Heartbeat: ${cause.message}`, "warn")); }, 10000); samplingTimer.current = window.setInterval(() => { void sendFrame(claimed, started).catch((cause) => log(`Sample failed: ${cause.message}`, "warn")); }, 2000); await sendFrame(claimed, started); });
  const stopMonitoring = async () => { if (samplingTimer.current) clearInterval(samplingTimer.current); if (heartbeatTimer.current) clearInterval(heartbeatTimer.current); samplingTimer.current = heartbeatTimer.current = null; if (session) await api(settings, `/api/monitoring/sessions/${session.sessionId}/release`, { ...json({}), headers: { "x-monitoring-token": session.leaseToken } }).catch(() => undefined); streamRef.current?.getTracks().forEach((track) => track.stop()); setMonitoring(false); setSession(null); setEpisode(null); log("Monitoring stopped", "info"); };
  useEffect(() => () => { if (samplingTimer.current) clearInterval(samplingTimer.current); if (heartbeatTimer.current) clearInterval(heartbeatTimer.current); streamRef.current?.getTracks().forEach((track) => track.stop()); }, []);

  const stages: Array<{ id: Stage; label: string }> = [{ id: "connect", label: "Connect" }, { id: "register", label: "Register" }, { id: "monitor", label: "Monitor" }, { id: "alerts", label: "Alerts" }];
  return <main className="app-shell"><header><div><h1>LitterSpot API sandbox</h1><p>Developer-only test UI for Camera Creation, monitoring and Alerts.</p></div><div className="header-readouts"><Scope label="API" value={token ? "connected" : "not connected"} /><Scope label="Site" value={profile?.siteId ?? "not selected"} /><Scope label="Sampling" value={monitoring ? `sample ${sequence.current}` : "stopped"} /></div></header>
    <nav aria-label="Sandbox stages">{stages.map((item) => <button key={item.id} className={stage === item.id ? "selected" : ""} onClick={() => { setStage(item.id); if (item.id === "alerts" && token) void run("Alerts refreshed", refreshAlerts); }}>{item.label}</button>)}</nav>
    {error && <div className="error-strip"><strong>Signal fault</strong><span>{error}</span><button onClick={() => setError("")}>Clear</button></div>}
    {stage === "connect" && <section className="stage connect-stage"><div className="panel intro"><h2>Connect</h2><p>Credentials stay in this browser session. The password is never stored.</p></div><form onSubmit={(event) => { event.preventDefault(); void connect(); }} className="control-rack"><label>Node API<input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} /></label><label>Firebase Web API key<input value={apiKey} onChange={(event) => setApiKey(event.target.value)} required /></label><label>Root Supervisor email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><Button tone="primary" type="submit" disabled={busy}>Connect</Button></form></section>}
    {stage === "register" && <section className="stage"><div className="stage-heading"><div><h2>Register a measured Camera scene</h2><p>Place the Camera, capture its reference, then trace walkable floor and physical bins.</p></div><Scope label="Draft" value={draft?.id ?? "not started"} /></div><div className="register-layout"><div className="signal-screen"><SiteMap map={map} selected={placement} onSelect={setPlacement} /></div><div className="control-rack"><label>Camera name<input value={cameraName} onChange={(event) => setCameraName(event.target.value)} /></label><label>Source<select value={sourceType} onChange={(event) => setSourceType(event.target.value as any)}><option value="laptop_camera">Laptop Camera</option><option value="looped_video">Looped video</option></select></label><Scope label="Placement" value={placement ? `${placement.xMeters.toFixed(1)}, ${placement.yMeters.toFixed(1)} m` : "click map"} /><Button tone="primary" onClick={() => void startDraft()} disabled={busy || Boolean(draft)}>Start Camera Draft</Button></div></div>
      {draft && <div className="registration-workbench"><div className="media-bench"><div className="video-frame"><video ref={referenceVideo} muted playsInline controls={sourceType === "looped_video"} /></div><div className="button-row">{sourceType === "laptop_camera" ? <><Button onClick={() => void openWebcam()}>Open webcam</Button><Button tone="warning" onClick={stopWebcam} disabled={!streamRef.current}>Stop webcam</Button></> : <><label className="file-button">Choose source video<input type="file" accept="video/mp4,video/webm" onChange={(event) => event.target.files?.[0] && void loadSourceFile(event.target.files[0])} /></label><Button onClick={() => void uploadSource()} disabled={!sourceFile || sourceStored}>{sourceStored ? "Source stored" : "Store source"}</Button></>}<Button onClick={() => void captureReference()}>Capture current frame</Button><label className="file-button">Choose reference image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => event.target.files?.[0] && chooseReference(event.target.files[0])} /></label><Button onClick={() => void uploadReference()} disabled={!referenceFile || referenceStored}>{referenceStored ? "Reference stored" : "Store reference"}</Button></div></div>{referenceUrl && <div className="plot-bench"><RegistrationPlot imageUrl={referenceUrl} floor={floor} bins={bins} currentBin={currentBin} mode={plotMode} onMode={setPlotMode} onPoint={(point) => plotMode === "floor" ? setFloor((items) => [...items, point]) : setCurrentBin((items) => [...items, point])} onLockBin={() => { setBins((items) => [...items, { binId: `bin-${items.length + 1}`, displayName: `Physical bin ${items.length + 1}`, binType: "unknown", binPolygon: currentBin }]); setCurrentBin([]); }} onReset={() => { setFloor([]); setBins([]); setCurrentBin([]); }} /><div className="button-row"><Button onClick={() => void saveRegistration()} disabled={floor.length < 3}>Save geometry</Button><Button tone="primary" onClick={() => void validateAndPublish()} disabled={busy || floor.length < 3 || !referenceFile}>Store, validate and publish</Button></div></div>}</div>}
    </section>}
    {token && <CameraRuntimeSandbox settings={settings} visible={stage === "monitor"} />}
    {stage === "alerts" && <section className="stage"><div className="stage-heading"><div><h2>Inspect qualified Alerts</h2><p>Each row is one active or historical Camera-and-issue condition, not one raw detection.</p></div><Button onClick={() => void run("Alerts refreshed", refreshAlerts)}>Refresh Alerts</Button></div><div className="alert-table"><div className="table-head"><span>Condition</span><span>Camera / Zone</span><span>Status</span><span>Evidence</span></div>{alerts.length === 0 ? <div className="empty">No Alerts have crossed policy thresholds.</div> : alerts.map((alert) => <div className="alert-row" key={alert.id}><span><strong>{alert.observedCondition}</strong><small>{alert.severity} · score {Number(alert.priorityScore ?? 0).toFixed(0)}</small></span><span><strong>{alert.cameraNameSnapshot}</strong><small>{alert.zoneNameSnapshot}</small></span><span className={`status ${alert.status}`}>{alert.status}</span><span>{alert.evidence?.mediaId ? <button onClick={async () => { const blob = await authorizedBlob(settings, `/api/media/${alert.evidence.mediaId}/content`); window.open(URL.createObjectURL(blob), "_blank"); }}>Open frame</button> : "No frame"}</span></div>)}</div></section>}
    <aside className="event-log"><div><h2>Activity log</h2><button onClick={() => setLogs([])}>Clear</button></div>{logs.length === 0 ? <p>No activity recorded.</p> : logs.map((item, index) => <p key={`${item.at}-${index}`} className={item.level}><time>{item.at}</time>{item.message}</p>)}</aside><canvas ref={captureCanvas} hidden /></main>;
}
