import { useEffect, useMemo, useRef, useState, type ChangeEvent, type MouseEvent } from "react";
import { SiteMapViewer } from "../components/SiteMapViewer";
import { deleteCameraDraft, fetchCameraDetail, getCameraDraft, getCameraDraftForCamera, getOperationsReadModel, publishCameraDraft, saveCameraDraftRegistration, startCameraDraft, uploadCameraDraftReference, uploadCameraDraftSourceVideo, validateCameraDraft, type CameraDraft, type OperationsReadModel, type OperationsPoint, type RegisteredBin, type OperationsZone } from "../services/api/operations";
import { validateZoneCandidate } from "../services/api/mapGeometry";
import { loadAuthenticatedMedia, releaseAuthenticatedMedia } from "../services/api/media";
import { ApiError } from "../services/api/errors";
import "./camera-creation.css";
import "./camera-zone-planner.css";

type Point = { x: number; y: number };
type Step = "location" | "source" | "plot" | "review";
type CameraWorkflowKind = "create" | "reconfigure" | "physical_move";
type LaptopCameraState = "closed" | "opening" | "open";
const createSteps: Array<{ id: Step; number: string; label: string }> = [{ id: "location", number: "01", label: "Place Camera" }, { id: "source", number: "02", label: "Reference" }, { id: "plot", number: "03", label: "Plot regions" }, { id: "review", number: "04", label: "Validate & publish" }];
const reconfigurationSteps: Array<{ id: Step; number: string; label: string }> = [{ id: "source", number: "01", label: "Reference" }, { id: "plot", number: "02", label: "Plot regions" }, { id: "review", number: "03", label: "Validate & publish" }];

export function cameraWorkflowSteps(kind: CameraWorkflowKind) {
  return kind === "create" ? createSteps : reconfigurationSteps;
}

export function laptopCameraControlLabel(state: LaptopCameraState) {
  return state === "open" ? "Close laptop Camera" : state === "opening" ? "Opening Camera…" : "Open laptop Camera";
}

export function laptopCaptureEnabled(input: { state: LaptopCameraState; frameReady: boolean; busy: boolean }) {
  return input.state === "open" && input.frameReady && !input.busy;
}

export function recoverableCameraDraftId(error: unknown) {
  if (!(error instanceof ApiError) || error.status !== 409 || !error.details || typeof error.details !== "object") return null;
  const details = error.details as { code?: unknown; draftId?: unknown };
  return details.code === "camera_draft_exists" && typeof details.draftId === "string" ? details.draftId : null;
}

const pointInPolygon = (point: Point, polygon: Point[]) => { let inside = false; for (let index = 0, previous = polygon.length - 1; index < polygon.length; previous = index++) { const a = polygon[index]; const b = polygon[previous]; if ((a.y > point.y) !== (b.y > point.y) && point.x < (b.x - a.x) * (point.y - a.y) / (b.y - a.y) + a.x) inside = !inside; } return inside; };
const polygonValid = (points: Point[]) => points.length >= 3 && Math.abs(points.reduce((sum, point, index) => { const next = points[(index + 1) % points.length]; return sum + point.x * next.y - next.x * point.y; }, 0)) > 0.0001;
const toMapPoint = (point: Point, size: { widthMeters: number; heightMeters: number }): OperationsPoint => ({ xMeters: Number((point.x / 100 * size.widthMeters).toFixed(2)), yMeters: Number((point.y / 100 * size.heightMeters).toFixed(2)) });
const toPercentPoint = (point: OperationsPoint, size: { widthMeters: number; heightMeters: number }): Point => ({ x: point.xMeters / size.widthMeters * 100, y: point.yMeters / size.heightMeters * 100 });
const labelFor = (sourceType: "laptop_camera" | "looped_video") => sourceType === "laptop_camera" ? "Laptop Camera" : "Looped video";

function imageDimensions(file: File) { return new Promise<{ width: number; height: number; url: string }>((resolve, reject) => { const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => resolve({ width: image.naturalWidth, height: image.naturalHeight, url }); image.onerror = () => { URL.revokeObjectURL(url); reject(new Error("The reference image could not be decoded.")); }; image.src = url; }); }
function captureFrame(video: HTMLVideoElement, name: string) { return new Promise<File>((resolve, reject) => { if (!video.videoWidth || !video.videoHeight) return reject(new Error("Wait for the video frame to load before capturing it.")); const canvas = document.createElement("canvas"); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height); canvas.toBlob((blob) => blob ? resolve(new File([blob], name, { type: "image/jpeg" })) : reject(new Error("The browser could not create the reference frame.")), "image/jpeg", .9); }); }

export function zoneAtPoint(point: Point, zones: OperationsZone[], size: { widthMeters: number; heightMeters: number }) {
  return zones.find((zone) => pointInPolygon(point, zone.polygon.map((vertex) => ({ x: vertex.xMeters / size.widthMeters * 100, y: vertex.yMeters / size.heightMeters * 100 }))));
}

export function cameraPlacementsForRegistration<T extends { cameraId: string }>(placements: T[], cameraId?: string | null) {
  return cameraId ? placements.filter((placement) => placement.cameraId !== cameraId) : placements;
}

function SiteMap({ siteMap, zones, point, selectedZoneId, selectingZone, excludedCameraId, onSelectZone, onPoint }: { siteMap: OperationsReadModel["siteMap"]; zones: OperationsZone[]; point: Point | null; selectedZoneId: string; selectingZone: boolean; excludedCameraId?: string | null; onSelectZone: (zoneId: string) => void; onPoint: (point: Point) => void }) {
  const size = siteMap.revision;
  return <div className="camera-zone-map current-camera-site-map shared"><SiteMapViewer compact boundary={size} gridSizeMeters={size.gridSizeMeters} background={siteMap.background ?? null} backgroundContentUrl={siteMap.background?.contentUrl ?? (size.backgroundMediaId ? `/api/media/${encodeURIComponent(size.backgroundMediaId)}/content` : null)} backgroundTransform={size.backgroundTransform ?? null} zones={zones.map((zone) => ({ id: zone.zoneId, name: zone.zoneNameSnapshot, polygon: zone.polygon }))} cameras={cameraPlacementsForRegistration(siteMap.cameraPlacements, excludedCameraId)} selectedZoneId={selectedZoneId} onSelectZone={selectingZone ? onSelectZone : undefined} pointMarker={point ? { point: toMapPoint(point, size), label: "Camera location", tone: "camera" } : null} onPlacePoint={!selectingZone ? (value) => onPoint(toPercentPoint(value, size)) : undefined} /><p className="camera-zone-map-instruction">{selectingZone ? "Pan or zoom, then select a Zone boundary or use the Zone list." : "Camera placement mode is active. Pan or zoom with the controls, then place the Camera inside the selected Zone."}</p></div>;
}

function ZonePlanner({ siteMap, zones, boundary, issues, excludedCameraId, onPoint, onUndo, onClear }: { siteMap: OperationsReadModel["siteMap"]; zones: OperationsZone[]; boundary: Point[]; issues: Array<{ message: string }>; excludedCameraId?: string | null; onPoint: (point: Point) => void; onUndo: () => void; onClear: () => void }) {
  const size = siteMap.revision;
  const candidate = { id: "provisional-zone", name: "New Zone", polygon: boundary.map((point) => toMapPoint(point, size)) };
  return <div className="camera-zone-map current-camera-zone-planner shared">
    <SiteMapViewer compact boundary={size} gridSizeMeters={size.gridSizeMeters} background={siteMap.background ?? null} backgroundContentUrl={siteMap.background?.contentUrl ?? (size.backgroundMediaId ? `/api/media/${encodeURIComponent(size.backgroundMediaId)}/content` : null)} backgroundTransform={size.backgroundTransform ?? null} zones={[...zones.map((zone) => ({ id: zone.zoneId, name: zone.zoneNameSnapshot, polygon: zone.polygon })), candidate]} cameras={cameraPlacementsForRegistration(siteMap.cameraPlacements, excludedCameraId)} drawingZoneId={candidate.id} conflictingZoneIds={issues.length ? new Set([candidate.id]) : undefined} onAddZonePoint={(point) => onPoint(toPercentPoint(point, size))} />
    <div className="current-camera-zone-tools"><span>{boundary.length} point{boundary.length === 1 ? "" : "s"}</span><button type="button" onClick={(event) => { event.stopPropagation(); onUndo(); }} disabled={!boundary.length}>Undo</button><button type="button" onClick={(event) => { event.stopPropagation(); onClear(); }} disabled={!boundary.length}>Clear</button></div>
    <p>{issues[0]?.message ?? "Plot at least three points. The new Zone cannot overlap or touch another Zone."}</p>
  </div>;
}

function PlotCanvas({ imageUrl, width, height, floor, bins, mode, pending, onPoint }: { imageUrl: string; width: number; height: number; floor: Point[]; bins: RegisteredBin[]; mode: "floor" | "bin"; pending: Point[]; onPoint: (point: Point) => void }) {
  const click = (event: MouseEvent<HTMLDivElement>) => { const box = event.currentTarget.getBoundingClientRect(); onPoint({ x: Math.max(0, Math.min(1, (event.clientX - box.left) / box.width)), y: Math.max(0, Math.min(1, (event.clientY - box.top) / box.height)) }); };
  const polygon = (points: Point[]) => points.map((point) => `${point.x * 100},${point.y * 100}`).join(" ");
  return <div className="current-camera-plot" style={{ aspectRatio: `${width}/${height}` }} onClick={click} role="application" tabIndex={0} aria-label={`Plot ${mode === "floor" ? "the walkable floor" : "a bin"} on the reference image`}><img src={imageUrl} alt="Camera reference" /><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{polygonValid(floor) && <polygon className="floor" points={polygon(floor)} />}{bins.map((bin) => <polygon className="bin" points={polygon(bin.binPolygon)} key={bin.binId} />)}{pending.length > 1 && <polyline className={`pending ${mode}`} points={polygon(pending)} />}{pending.map((point, index) => <circle className={`pending ${mode}`} cx={point.x * 100} cy={point.y * 100} r=".85" key={`${point.x}-${point.y}-${index}`} />)}</svg><span>Click to add a point · Finish after at least 3 points</span></div>;
}

export function CameraCreationPage({ cameraId, initialDraft, canCreateCamera = true, onClose, onPublished }: { cameraId?: string; initialDraft?: CameraDraft; canCreateCamera?: boolean; onClose: () => void; onPublished?: (cameraId: string) => void | Promise<void> }) {
  const requestedCameraId = cameraId ?? initialDraft?.cameraId ?? new URLSearchParams(location.hash.split("?")[1] ?? "").get("cameraId"); const [kind, setKind] = useState<"create" | "reconfigure">(requestedCameraId ? "reconfigure" : "create"); const [recoveredWorkflowKind, setRecoveredWorkflowKind] = useState<CameraWorkflowKind>(); const workflowKind: CameraWorkflowKind = initialDraft?.kind === "physical_move" || recoveredWorkflowKind === "physical_move" ? "physical_move" : kind; const workflowSteps = cameraWorkflowSteps(workflowKind); const [step, setStep] = useState<Step>(requestedCameraId || initialDraft ? "source" : "location"); const [siteMap, setSiteMap] = useState<OperationsReadModel["siteMap"]>(); const [zones, setZones] = useState<OperationsZone[]>([]); const [mapSize, setMapSize] = useState({ widthMeters: 1, heightMeters: 1 }); const [cameraCount, setCameraCount] = useState(0); const [name, setName] = useState(initialDraft?.name ?? "Camera 1"); const [description, setDescription] = useState(initialDraft?.description ?? ""); const [sourceType, setSourceType] = useState<"laptop_camera" | "looped_video">(initialDraft?.source.type ?? "laptop_camera"); const [placement, setPlacement] = useState<Point | null>(null); const [selectedZoneId, setSelectedZoneId] = useState(initialDraft?.placement?.zoneId ?? ""); const [locationPlotting, setLocationPlotting] = useState(Boolean(initialDraft)); const [zoneMode, setZoneMode] = useState<"existing" | "new">("existing"); const [newZoneName, setNewZoneName] = useState(""); const [newZoneBoundary, setNewZoneBoundary] = useState<Point[]>([]); const [provisionalZone, setProvisionalZone] = useState<OperationsZone>(); const [draft, setDraft] = useState<CameraDraft | undefined>(initialDraft); const [reference, setReference] = useState<{ file?: File; url: string; width: number; height: number; retained?: boolean }>(); const [videoFile, setVideoFile] = useState<File>(); const [videoUrl, setVideoUrl] = useState<string>(); const [floor, setFloor] = useState<Point[]>([]); const [bins, setBins] = useState<RegisteredBin[]>([]); const [pending, setPending] = useState<Point[]>([]); const [mode, setMode] = useState<"floor" | "bin">("floor"); const [binName, setBinName] = useState("Bin 1"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [note, setNote] = useState(""); const webcam = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | undefined>(undefined); const video = useRef<HTMLVideoElement>(null); const videoInput = useRef<HTMLInputElement>(null); const retainedMediaKeys = useRef<string[]>([]);
  const [laptopCameraState, setLaptopCameraState] = useState<LaptopCameraState>("closed");
  const [laptopFrameReady, setLaptopFrameReady] = useState(false);
  useEffect(() => {
    const controller = new AbortController();
    void (async () => {
      const model = await getOperationsReadModel(controller.signal);
      setSiteMap(model.siteMap); setZones(model.siteMap.zones); setMapSize(model.siteMap.revision); setCameraCount(model.cameras.length);
      const existing = requestedCameraId ? model.cameras.find((camera) => camera.id === requestedCameraId) : undefined;
      if (!existing || !requestedCameraId) { setSourceType("looped_video"); setName(`Camera ${model.cameras.length + 1}`); return; }
      const unfinishedDraft = (await getCameraDraftForCamera(requestedCameraId, controller.signal)).draft;
      if (unfinishedDraft) { setDraft(unfinishedDraft); setRecoveredWorkflowKind(unfinishedDraft.kind); setName(unfinishedDraft.name); setDescription(unfinishedDraft.description ?? ""); setSourceType(unfinishedDraft.source.type); setNote(unfinishedDraft.kind === "physical_move" ? "Continuing the unfinished Physical Camera Move. Capture a fresh reference before plotting regions." : "Continuing the unfinished Camera View reconfiguration."); }
      const detail = await fetchCameraDetail(requestedCameraId, controller.signal);
      const camera = detail.camera;
      setKind("reconfigure");
      if (!unfinishedDraft) { setName(camera.name); setDescription(camera.description ?? ""); setSourceType(camera.sourceType); }
      const effectivePlacement = unfinishedDraft?.placement ?? initialDraft?.placement ?? camera.placement;
      if (effectivePlacement) { setSelectedZoneId(effectivePlacement.zoneId); setPlacement(toPercentPoint(effectivePlacement.point, model.siteMap.revision)); setLocationPlotting(true); }
      const registration = camera.registration;
      if (unfinishedDraft?.kind !== "physical_move" && initialDraft?.kind !== "physical_move" && registration?.referenceMediaId && registration.sourceWidth && registration.sourceHeight) {
        const key = `camera-active-reference:${requestedCameraId}:${registration.referenceMediaId}`;
        retainedMediaKeys.current.push(key);
        const url = await loadAuthenticatedMedia(key, `/api/media/${encodeURIComponent(registration.referenceMediaId)}/content`, controller.signal);
        setReference({ url, width: registration.sourceWidth, height: registration.sourceHeight, retained: true });
        setFloor(registration.walkableFloorPolygon ?? []); setBins(registration.bins ?? []);
      }
      if (camera.sourceType === "looped_video" && camera.source?.contentUrl) {
        const key = `camera-active-source:${requestedCameraId}:${camera.source.sourceMediaId ?? "active"}`;
        retainedMediaKeys.current.push(key);
        setVideoUrl(await loadAuthenticatedMedia(key, camera.source.contentUrl, controller.signal));
      }
    })().catch((reason) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Camera Creation data could not be loaded."); });
    return () => { controller.abort(); stream.current?.getTracks().forEach((track) => track.stop()); retainedMediaKeys.current.forEach(releaseAuthenticatedMedia); retainedMediaKeys.current = []; };
  }, [initialDraft, requestedCameraId]);
  const availableZones = useMemo(() => provisionalZone ? [...zones, provisionalZone] : zones, [provisionalZone, zones]);
  const placementZone = useMemo(() => placement ? availableZones.find((zone) => pointInPolygon(placement, zone.polygon.map((vertex) => ({ x: vertex.xMeters / mapSize.widthMeters * 100, y: vertex.yMeters / mapSize.heightMeters * 100 })))) : undefined, [availableZones, mapSize, placement]);
  const provisionalZoneIssues = useMemo(() => validateZoneCandidate({ id: "provisional-zone", name: newZoneName.trim() || "New Zone", polygon: newZoneBoundary.map((point) => toMapPoint(point, mapSize)) }, zones.map((zone) => ({ id: zone.zoneId, name: zone.zoneNameSnapshot, polygon: zone.polygon })), mapSize), [mapSize, newZoneBoundary, newZoneName, zones]);
  const saveProvisionalZone = () => {
    if (!canCreateCamera) { setError("Root Supervisor access is required to create a new Zone."); return; }
    if (!siteMap || newZoneName.trim().length < 2 || provisionalZoneIssues.length) { setError(provisionalZoneIssues[0]?.message ?? "Enter a Zone name and plot at least three points for its boundary."); return; }
    const zoneId = `zone-${globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
    const newZone = { id: zoneId, zoneId, zoneNameSnapshot: newZoneName.trim(), polygon: newZoneBoundary.map((point) => toMapPoint(point, mapSize)) };
    setProvisionalZone(newZone); setSelectedZoneId(zoneId); setPlacement(null); setLocationPlotting(true); setZoneMode("existing"); setError(""); setNote(`${newZone.zoneNameSnapshot} is provisional. It will only be created when the Camera is published on Page 4.`);
  };
  const stopWebcam = () => {
    stream.current?.getTracks().forEach((track) => track.stop());
    stream.current = undefined;
    if (webcam.current) webcam.current.srcObject = null;
    setLaptopFrameReady(false);
    setLaptopCameraState("closed");
  };
  const changeSourceType = (next: "laptop_camera" | "looped_video") => {
    if (next === sourceType) return;
    stopWebcam();
    setSourceType(next); setReference(undefined); setVideoFile(undefined); setVideoUrl(undefined); setFloor([]); setBins([]); setPending([]); setError("");
    setNote("The Camera source changed. Capture a new reference and plot fresh floor and bin regions.");
  };
  const draftStart = async () => { if (kind === "create" && !canCreateCamera) { setError("Root Supervisor access is required to create a new Camera. Open an existing Camera to re-register it."); return undefined; } if (!name.trim() || kind === "create" && (!placement || !placementZone || placementZone.zoneId !== selectedZoneId)) { setError("Name the Camera and place it inside the selected Zone."); return undefined; } setBusy(true); setError(""); try { const result = await startCameraDraft({ kind, ...(kind === "reconfigure" && requestedCameraId ? { cameraId: requestedCameraId } : {}), name: name.trim(), description: description.trim() || null, sourceType, placement: kind === "create" && placement ? { point: toMapPoint(placement, mapSize) } : null, provisionalZone: provisionalZone ? { zoneId: provisionalZone.zoneId, zoneNameSnapshot: provisionalZone.zoneNameSnapshot, polygon: provisionalZone.polygon } : null }); setDraft(result.draft); if (kind === "create") setStep("source"); setNote(kind === "create" ? "Camera Draft started. Nothing becomes operational until Page 4." : "View reconfiguration started. The Camera location and identity remain unchanged."); return result.draft; } catch (reason) { const existingDraftId = recoverableCameraDraftId(reason); if (existingDraftId) { try { const existing = (await getCameraDraft(existingDraftId)).draft; setDraft(existing); setRecoveredWorkflowKind(existing.kind); setStep("source"); if (existing.kind === "physical_move") { setReference(undefined); setFloor([]); setBins([]); setPending([]); if (existing.placement) { setSelectedZoneId(existing.placement.zoneId); setPlacement(toPercentPoint(existing.placement.point, mapSize)); } } setNote(existing.kind === "physical_move" ? "Continuing the unfinished Physical Camera Move. Capture a fresh reference before plotting regions." : "Continuing the unfinished Camera View reconfiguration."); return existing; } catch (recoveryError) { setError(recoveryError instanceof Error ? recoveryError.message : "The unfinished Camera Draft could not be recovered."); return undefined; } } setError(reason instanceof Error ? reason.message : "The Camera Draft could not be started."); return undefined; } finally { setBusy(false); } };
  const ensureDraft = async () => draft ?? await draftStart();
  const uploadReference = async (file: File) => { const activeDraft = await ensureDraft(); if (!activeDraft) return; setBusy(true); setError(""); try { const [dimensions] = await Promise.all([imageDimensions(file), uploadCameraDraftReference(activeDraft.id, file)]); if (reference?.file) URL.revokeObjectURL(reference.url); setReference({ file, url: dimensions.url, width: dimensions.width, height: dimensions.height }); setFloor([]); setBins([]); setPending([]); setNote("Replacement reference saved. Plot a fresh floor boundary and any visible bins."); } catch (reason) { setError(reason instanceof Error ? reason.message : "The reference could not be stored."); } finally { setBusy(false); } };
  const chooseVideo = async (file: File) => { const activeDraft = await ensureDraft(); if (!activeDraft) return; setBusy(true); setError(""); try { const response = await uploadCameraDraftSourceVideo(activeDraft.id, file); if (videoFile && videoUrl) URL.revokeObjectURL(videoUrl); const url = URL.createObjectURL(file); setVideoFile(file); setVideoUrl(url); setReference(undefined); setFloor([]); setBins([]); setPending([]); setNote(`Replacement looped source saved (${Math.round(response.source.durationSeconds)} seconds). Pause at a clear frame and capture a new reference.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "The looped video could not be stored."); } finally { setBusy(false); } };
  const chooseVideoFromInput = (event: ChangeEvent<HTMLInputElement>) => { const file = event.currentTarget.files?.[0]; event.currentTarget.value = ""; if (file) void chooseVideo(file); };
  const startWebcam = async () => { if (laptopCameraState === "open") { stopWebcam(); return; } if (laptopCameraState === "opening") return; setLaptopFrameReady(false); setLaptopCameraState("opening"); setError(""); try { const nextStream = await navigator.mediaDevices.getUserMedia({ video: true, audio: false }); stream.current = nextStream; const track = nextStream.getVideoTracks()[0]; track?.addEventListener("ended", () => { if (stream.current === nextStream) stopWebcam(); }, { once: true }); if (webcam.current) { webcam.current.srcObject = nextStream; await webcam.current.play().catch(() => undefined); } setLaptopCameraState("open"); } catch (reason) { stopWebcam(); setError(reason instanceof Error ? reason.message : "The laptop Camera could not be opened."); } };
  const captureWebcam = async () => { if (!webcam.current || !laptopCaptureEnabled({ state: laptopCameraState, frameReady: laptopFrameReady, busy })) return; try { await uploadReference(await captureFrame(webcam.current, "laptop-reference.jpg")); } catch (reason) { setError(reason instanceof Error ? reason.message : "The laptop reference could not be captured."); } finally { stopWebcam(); } };
  const addPoint = (point: Point) => setPending((points) => [...points, point]);
  const removeFloorRegion = () => { setFloor([]); setPending([]); setMode("floor"); setError(""); setNote("Floor region removed. Plot a replacement before continuing."); };
  const finishPolygon = () => { if (!polygonValid(pending)) { setError("Plot at least three distinct points before finishing the polygon."); return; } if (mode === "floor") { setFloor(pending); setMode("bin"); setBinName(`Bin ${bins.length + 1}`); setNote("Floor saved. Add any visible physical bins, or continue to review."); } else { setBins((items) => [...items, { binId: `bin-${items.length + 1}`, displayName: binName.trim() || `Bin ${items.length + 1}`, binType: "unknown", binPolygon: pending }]); setBinName(`Bin ${bins.length + 2}`); setNote("Bin saved. Add another bin or continue to review."); } setPending([]); setError(""); };
  const saveAndValidate = async () => { if (!draft || !reference || !polygonValid(floor)) { setError("Upload a reference and complete the walkable-floor polygon first."); return; } setBusy(true); setError(""); try { await saveCameraDraftRegistration(draft.id, { sourceWidth: reference.width, sourceHeight: reference.height, walkableFloorPolygon: floor, bins }); const validation = await validateCameraDraft(draft.id); if (!validation.valid) { setError(`Draft validation failed: ${validation.errors.join(", ")}`); return; } setStep("review"); setNote("Draft is valid and ready to publish."); } catch (reason) { setError(reason instanceof Error ? reason.message : "The registration could not be validated."); } finally { setBusy(false); } };
  const publish = async () => { if (!draft) return; setBusy(true); setError(""); try { const result = await publishCameraDraft(draft.id); setNote("Camera published successfully."); await onPublished?.(result.result.cameraId); if (!onPublished) location.hash = `/cameras?cameraId=${encodeURIComponent(result.result.cameraId)}`; } catch (reason) { setError(reason instanceof Error ? reason.message : "The Camera could not be published."); } finally { setBusy(false); } };
  const close = async () => { if (busy) return; setBusy(true); setError(""); try { if (draft) await deleteCameraDraft(draft.id); stopWebcam(); if (reference?.file) URL.revokeObjectURL(reference.url); if (videoFile && videoUrl) URL.revokeObjectURL(videoUrl); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The unfinished Camera registration could not be cancelled."); } finally { setBusy(false); } };
  const sourceReady = Boolean(reference && (sourceType === "laptop_camera" || videoUrl)); const floorReady = polygonValid(floor); const plotReady = sourceReady && floorReady; const reviewReady = plotReady;
  const goBack = () => { stopWebcam(); setStep(step === "review" ? "plot" : "source"); };
  const next = async () => {
    setError("");
    if (step === "location") draft ? setStep("source") : await draftStart();
    else if (step === "source" && reference) { const activeDraft = await ensureDraft(); if (activeDraft) { if (activeDraft.kind === "physical_move" && !reference.file) return; stopWebcam(); setStep("plot"); } }
    else if (step === "plot") await saveAndValidate();
    else if (step === "review") await publish();
  };
  const nextDisabled = busy || step === "location" && !draft && (!locationPlotting || !placement || !placementZone || placementZone.zoneId !== selectedZoneId || !name.trim()) || step === "source" && !sourceReady || step === "plot" && !floorReady || step === "review" && !reviewReady;
  const nextLabel = busy ? step === "location" ? "Saving draft…" : step === "plot" ? "Validating…" : step === "review" ? "Publishing…" : "Saving reference…" : step === "location" ? draft ? "Return to reference →" : "Continue to reference →" : step === "source" ? "Continue to region plotting →" : step === "plot" ? "Continue to validation →" : "Validate & publish →";

  return <div className="camera-modal-scrim camera-registration-scrim" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) close(); }}>
    <section className="camera-add-modal camera-registration-wizard" role="dialog" aria-modal="true" aria-labelledby="camera-registration-title">
      <header><div><span>{workflowKind === "create" ? "NEW CAMERA" : workflowKind === "physical_move" ? "PHYSICAL CAMERA MOVE" : "CAMERA VIEW RECONFIGURATION"} · {siteMap?.siteName ?? "ACTIVE SITE"}</span><h2 id="camera-registration-title">{workflowKind === "create" ? "Create a new camera." : workflowKind === "physical_move" ? `Register ${name} at its new position.` : `Reconfigure ${name}'s view.`}</h2><p>{workflowKind === "physical_move" ? "Capture a fresh reference and plot the new physical view before the moved Camera becomes active." : workflowKind === "create" ? "Complete all four pages before this Camera becomes operational." : "Update the source, reference, floor, and bin regions without changing Camera placement or identity."}</p></div><button type="button" onClick={close} disabled={busy} aria-label="Close camera registration">×</button></header>
      <nav className={`camera-registration-progress ${workflowKind === "create" ? "four-steps" : "three-steps"}`} aria-label="Camera registration progress">{workflowSteps.map((item) => { const currentIndex = workflowSteps.findIndex((candidate) => candidate.id === step); const itemIndex = workflowSteps.findIndex((candidate) => candidate.id === item.id); const unlocked = itemIndex <= currentIndex || item.id === "source" && Boolean(draft) || item.id === "plot" && Boolean(draft) && sourceReady || item.id === "review" && Boolean(draft) && reviewReady; return <button type="button" key={item.id} className={step === item.id ? "active" : itemIndex < currentIndex ? "complete" : ""} disabled={!unlocked} onClick={() => { if (!unlocked) return; if (item.id !== "source") stopWebcam(); setStep(item.id); }}><b>{item.number}</b><span>{item.label}</span></button>; })}</nav>

      {step === "location" && <div className="camera-add-body with-zone-map registration-location-page">
        <section className="camera-modal-section camera-modal-location">
          <span className="camera-modal-step">01 / ZONE & LOCATION</span>
          {canCreateCamera && kind === "create" && <div className="camera-zone-mode" role="group" aria-label="Choose zone setup"><button type="button" disabled={Boolean(draft)} className={zoneMode === "existing" ? "active" : ""} onClick={() => setZoneMode("existing")}><b>Existing zone</b><small>Select a registered area on the map</small></button><button type="button" disabled={Boolean(draft)} className={zoneMode === "new" ? "active" : ""} onClick={() => setZoneMode("new")}><b>Create new zone</b><small>Name and outline a new area</small></button></div>}
          {zoneMode === "existing" ? <label>Cleaning zone<select disabled={Boolean(draft)} value={selectedZoneId} onChange={(event) => { setSelectedZoneId(event.target.value); setPlacement(null); setLocationPlotting(false); setError(""); }}><option value="" disabled>Select a zone</option>{availableZones.map((zone) => <option key={zone.id} value={zone.zoneId}>{zone.zoneNameSnapshot}{zone.zoneId === provisionalZone?.zoneId ? " · new" : ""}</option>)}</select></label> : <><label>New zone name<input disabled={Boolean(draft)} value={newZoneName} onChange={(event) => setNewZoneName(event.target.value)} placeholder="South concourse" minLength={2} /></label><button type="button" className="camera-provisional-zone-action primary" onClick={saveProvisionalZone} disabled={busy || newZoneName.trim().length < 2 || provisionalZoneIssues.length > 0}>Save Zone & place Camera →</button></>}
          <section className="camera-zone-planner">
            <header><div><span>{zoneMode === "new" ? "ZONE BOUNDARY" : locationPlotting ? "CAMERA LOCATION" : "SELECTED ZONE"}</span><strong>{draft ? "Camera placement saved." : zoneMode === "new" ? provisionalZoneIssues.length === 0 ? "New Zone boundary ready." : provisionalZoneIssues[0]?.message ?? "Outline the new Zone." : !selectedZoneId ? "Click a Zone on the map or choose one from the list." : !locationPlotting ? availableZones.find((zone) => zone.zoneId === selectedZoneId)?.zoneNameSnapshot : placementZone?.zoneNameSnapshot ?? "Place the Camera inside the selected Zone."}</strong></div><b className={draft || placement && placementZone?.zoneId === selectedZoneId || zoneMode === "new" && provisionalZoneIssues.length === 0 ? "ready" : ""}>{draft ? "Saved" : placement && placementZone?.zoneId === selectedZoneId || zoneMode === "new" && provisionalZoneIssues.length === 0 ? "Ready" : "Step 1"}</b></header>
            {zoneMode === "new" && siteMap ? <ZonePlanner siteMap={siteMap} zones={zones} boundary={newZoneBoundary} issues={provisionalZoneIssues} excludedCameraId={requestedCameraId} onPoint={(point) => { if (!draft) setNewZoneBoundary((current) => [...current, point]); }} onUndo={() => setNewZoneBoundary((current) => current.slice(0, -1))} onClear={() => setNewZoneBoundary([])} /> : siteMap ? <SiteMap siteMap={siteMap} zones={availableZones} point={placement} selectedZoneId={selectedZoneId} selectingZone={!locationPlotting} excludedCameraId={requestedCameraId} onSelectZone={(zoneId) => { if (draft) return; setSelectedZoneId(zoneId); setPlacement(null); setError(""); }} onPoint={(point) => { if (draft || !locationPlotting) return; const selected = availableZones.find((zone) => zone.zoneId === selectedZoneId); if (!selected || !pointInPolygon(point, selected.polygon.map((vertex) => ({ x: vertex.xMeters / mapSize.widthMeters * 100, y: vertex.yMeters / mapSize.heightMeters * 100 })))) { setError("Place the Camera inside the selected Zone."); return; } setPlacement(point); setError(""); }} /> : <div className="camera-map-loading">Loading the active Site Map…</div>}
            <div className="camera-zone-readout"><div><span>CAMERA COORDINATES</span><strong>{placement ? `X ${toMapPoint(placement, mapSize).xMeters} m` : "Not plotted"}</strong><small>{placement ? `Y ${toMapPoint(placement, mapSize).yMeters} m` : locationPlotting ? "Click the map to place" : "Select the Zone first"}</small></div><div><span>PAGE STATUS</span><strong>{draft ? "Draft placement saved" : placement && placementZone?.zoneId === selectedZoneId ? "Zone and location ready" : zoneMode === "new" && provisionalZoneIssues.length === 0 ? "Zone ready to save" : locationPlotting ? "Place the Camera" : "Complete Zone selection"}</strong><small>{placementZone?.zoneNameSnapshot ?? availableZones.find((zone) => zone.zoneId === selectedZoneId)?.zoneNameSnapshot ?? siteMap?.siteName}</small></div></div>
          </section>
        </section>
        {zoneMode === "existing" && !locationPlotting && <div className="camera-location-next existing"><button type="button" className="primary" disabled={!selectedZoneId || Boolean(draft)} onClick={() => { setLocationPlotting(true); setPlacement(null); setError(""); }}>Next: Plot camera location →</button></div>}
        <section className={`camera-modal-section camera-modal-details ${placement && placementZone?.zoneId === selectedZoneId ? "ready" : "locked"}`}><span className="camera-modal-step">02 / CAMERA DETAILS</span><div className="camera-modal-fields"><label>Camera name<input value={name} onChange={(event) => setName(event.target.value)} minLength={2} required disabled={Boolean(draft) || !placement || placementZone?.zoneId !== selectedZoneId} /></label><label>Source<select value={sourceType} onChange={(event) => changeSourceType(event.target.value as "laptop_camera" | "looped_video")} disabled={Boolean(draft) || kind === "create" && (!placement || placementZone?.zoneId !== selectedZoneId)}><option value="looped_video">Looped video</option><option value="laptop_camera">Laptop Camera</option></select></label><label>Coordinate X<input value={placement ? `${toMapPoint(placement, mapSize).xMeters} m` : "Set from map"} readOnly disabled /></label><label>Coordinate Y<input value={placement ? `${toMapPoint(placement, mapSize).yMeters} m` : "Set from map"} readOnly disabled /></label></div><label>Description <small>Optional</small><input value={description} onChange={(event) => setDescription(event.target.value)} disabled={Boolean(draft) || !placement || placementZone?.zoneId !== selectedZoneId} placeholder="What this Camera monitors" /></label><small className="camera-coverage-hint">{draft ? "This placement and Camera identity are saved in the active draft." : kind === "create" ? "New Cameras start disabled. Only one laptop Camera can be enabled at a time." : "Disable this Camera before changing source type. Replot the floor and bins for a changed view."}</small></section>
      </div>}

      {step === "source" && <div className="camera-registration-page reference-page">
        <section className="registration-media-workspace">
          <header><div><span>{workflowKind === "create" ? "02" : "01"} / REFERENCE SOURCE</span><h3>{labelFor(sourceType)}</h3><p>{sourceType === "laptop_camera" ? "Open the laptop Camera and capture a clear frame that shows the full monitoring area." : "Upload the demonstration video, pause on a clear frame, then capture it as the registration reference."}</p>{kind === "reconfigure" && <div className="registration-source-choice" role="group" aria-label="Camera source type"><button type="button" className={sourceType === "looped_video" ? "active" : ""} disabled={Boolean(draft) || busy} onClick={() => changeSourceType("looped_video")}>Looped video</button><button type="button" className={sourceType === "laptop_camera" ? "active" : ""} disabled={Boolean(draft) || busy} onClick={() => changeSourceType("laptop_camera")}>Laptop Camera</button></div>}</div><b className={sourceReady ? "ready" : ""}>{sourceReady ? "Reference ready" : "Reference required"}</b></header>
          {sourceType === "laptop_camera" ? <><video ref={webcam} autoPlay muted playsInline className="registration-video" onLoadedData={() => setLaptopFrameReady(true)} onPlaying={() => setLaptopFrameReady(true)} /><div className="registration-inline-actions"><button type="button" onClick={() => void startWebcam()} disabled={laptopCameraState === "opening" || busy}>{laptopCameraControlLabel(laptopCameraState)}</button><button type="button" className="primary" onClick={() => void captureWebcam()} disabled={!laptopCaptureEnabled({ state: laptopCameraState, frameReady: laptopFrameReady, busy })}>Capture current frame</button></div></> : <>
            <input ref={videoInput} className="registration-video-input" type="file" accept="video/mp4,video/quicktime,video/webm" onChange={chooseVideoFromInput} />
            {!videoUrl ? <button type="button" className="registration-upload" onClick={() => videoInput.current?.click()} disabled={busy}><strong>{busy ? "Uploading video…" : "Choose a looped video"}</strong><small>MP4, MOV or WebM</small></button> : <video ref={video} className="registration-video" src={videoUrl} controls playsInline />}
          </>}
        </section>
        <aside className="registration-side-panel">
          <header className="registration-preview-header"><span>REFERENCE PREVIEW</span>{sourceType === "looped_video" && videoUrl && <button type="button" onClick={() => videoInput.current?.click()} disabled={busy}>Change reference</button>}</header>
          {reference ? <><img src={reference.url} alt="Saved Camera reference" /><strong>Frame stored</strong><small>{reference.width} × {reference.height} pixels</small><p>This exact frame will be used to plot the floor and visible bins.</p></> : <div className="registration-empty"><strong>No reference yet</strong><p>Capture one clear frame before continuing.</p></div>}
          {sourceType === "looped_video" && videoUrl && <button type="button" className="primary registration-capture registration-preview-capture" disabled={busy} onClick={() => { if (video.current) void captureFrame(video.current, "video-reference.jpg").then(uploadReference).catch((reason) => setError(reason instanceof Error ? reason.message : "The video frame could not be captured.")); }}>Use current frame as reference</button>}
        </aside>
      </div>}

      {step === "plot" && reference && <div className="camera-registration-page plot-page"><section className="registration-media-workspace"><header><div><span>{workflowKind === "create" ? "03" : "02"} / FOOTAGE REGIONS</span><h3>{mode === "floor" ? "Plot the walkable floor." : "Plot visible bins."}</h3><p>{mode === "floor" ? "Only litter detections inside this boundary count toward the Camera workflow." : "Bin regions are optional. Add each physical bin visible in this Camera view."}</p></div><b className={floorReady ? "ready" : ""}>{floorReady ? `${bins.length} bins · floor ready` : "Floor required"}</b></header><PlotCanvas imageUrl={reference.url} width={reference.width} height={reference.height} floor={floor} bins={bins} mode={mode} pending={pending} onPoint={addPoint} /></section><aside className="registration-side-panel region-tools"><span>PLOTTING TOOLS</span><div className="camera-zone-mode"><button type="button" className={mode === "floor" ? "active" : ""} onClick={() => { setMode("floor"); setPending([]); }}><b>Floor region</b><small>Required monitoring boundary</small></button><button type="button" className={mode === "bin" ? "active" : ""} onClick={() => { setMode("bin"); setPending([]); }}><b>Bin region</b><small>{bins.length} registered</small></button></div>{mode === "bin" && <label>Bin display name<input value={binName} onChange={(event) => setBinName(event.target.value)} /></label>}<dl><div><dt>POINTS IN PROGRESS</dt><dd>{pending.length}</dd></div><div><dt>SAVED BINS</dt><dd>{bins.length}</dd></div></dl><div className="registration-tool-actions"><button type="button" onClick={() => setPending((points) => points.slice(0, -1))} disabled={!pending.length}>Undo point</button><button type="button" onClick={() => setPending([])} disabled={!pending.length}>Clear points</button><button type="button" className="primary" onClick={finishPolygon} disabled={!pending.length}>Finish {mode} region</button></div>{floorReady && <button type="button" className="registration-remove-floor" onClick={removeFloorRegion}>Remove floor region</button>}{bins.length > 0 && <button type="button" className="registration-remove-bin" onClick={() => setBins((items) => items.slice(0, -1))}>Remove last bin</button>}</aside></div>}

      {step === "review" && <div className="camera-registration-page review-page"><section className="registration-media-workspace"><header><div><span>{workflowKind === "create" ? "04" : "03"} / VALIDATE & PUBLISH</span><h3>Registration is ready.</h3><p>{workflowKind === "create" ? "Review the Camera placement and detection regions before publishing." : workflowKind === "physical_move" ? "Review the new placement, reference and detection regions before publishing the Physical Camera Move." : "Review the source and detection regions before publishing. Camera placement and identity stay unchanged."}</p></div><b className="ready">Validated</b></header>{reference && <PlotCanvas imageUrl={reference.url} width={reference.width} height={reference.height} floor={floor} bins={bins} mode="floor" pending={[]} onPoint={() => undefined} />}</section><aside className="registration-side-panel registration-summary"><span>REGISTRATION SUMMARY</span><dl><div><dt>CAMERA</dt><dd>{name}</dd></div><div><dt>ZONE</dt><dd>{placementZone?.zoneNameSnapshot ?? "Existing placement"}</dd></div><div><dt>SOURCE</dt><dd>{labelFor(sourceType)}</dd></div><div><dt>FLOOR REGION</dt><dd>{floor.length} points</dd></div><div><dt>REGISTERED BINS</dt><dd>{bins.length}</dd></div><div><dt>AFTER PUBLISHING</dt><dd>{kind === "create" ? "Monitoring disabled" : "Current monitoring setting retained"}</dd></div></dl><p>{workflowKind === "create" ? "Publishing creates the operational Camera, its placement, source, and registration." : workflowKind === "physical_move" ? "Publishing activates the Root-approved Camera position with this fresh source and registration." : "Publishing replaces the Camera source and registration. Its name, description, Zone, and Site Map position stay unchanged."}</p></aside></div>}

      {error && <p className="camera-modal-error" role="alert">{error}</p>}{note && <p className="camera-registration-note" role="status">{note}</p>}
      <footer className="camera-registration-footer"><p>{step === "location" ? "Place the Camera inside one active Zone. Camera creation remains a draft until Page 4." : step === "source" ? workflowKind === "reconfigure" ? "Camera placement and identity remain unchanged throughout this workflow." : "The reference should show the complete floor area and any bins you want to register." : step === "plot" ? "The floor region is required. Bin regions are optional." : workflowKind === "create" || workflowKind === "physical_move" ? "Publish only after the placement and overlays match the physical Camera view." : "Publish only after the reference and regions match the Camera view."}</p><div>{step === "location" || step === "source" && workflowKind !== "create" ? <button type="button" className="outline-button" onClick={close} disabled={busy}>Cancel</button> : <button type="button" className="outline-button" onClick={goBack} disabled={busy}>← Back</button>}<button type="button" className="primary" onClick={() => void next()} disabled={nextDisabled}>{nextLabel}</button></div></footer>
    </section>
  </div>;
}
