import { useEffect, useMemo, useRef, useState, type ChangeEvent, type MouseEvent } from "react";
import { deleteV2SiteMapDraft, getV2OperationsReadModel, publishV2CameraDraft, publishV2SiteMapDraft, saveV2CameraDraftRegistration, saveV2SiteMapDraft, startV2CameraDraft, uploadV2CameraDraftReference, uploadV2CameraDraftSourceVideo, validateV2CameraDraft, validateV2SiteMapDraft, type V2CameraDraft, type V2OperationsReadModel, type V2Point, type V2RegisteredBin, type V2Zone } from "../services/v2/operations";
import "./v2-camera-creation.css";
import "./v2-camera-zone-planner.css";

type Point = { x: number; y: number };
type Step = "location" | "source" | "plot" | "review";
const steps: Array<{ id: Step; number: string; label: string }> = [{ id: "location", number: "01", label: "Place Camera" }, { id: "source", number: "02", label: "Reference" }, { id: "plot", number: "03", label: "Plot regions" }, { id: "review", number: "04", label: "Validate & publish" }];

const pointInPolygon = (point: Point, polygon: Point[]) => { let inside = false; for (let index = 0, previous = polygon.length - 1; index < polygon.length; previous = index++) { const a = polygon[index]; const b = polygon[previous]; if ((a.y > point.y) !== (b.y > point.y) && point.x < (b.x - a.x) * (point.y - a.y) / (b.y - a.y) + a.x) inside = !inside; } return inside; };
const polygonValid = (points: Point[]) => points.length >= 3 && Math.abs(points.reduce((sum, point, index) => { const next = points[(index + 1) % points.length]; return sum + point.x * next.y - next.x * point.y; }, 0)) > 0.0001;
const toMapPoint = (point: Point, size: { widthMeters: number; heightMeters: number }): V2Point => ({ xMeters: Number((point.x / 100 * size.widthMeters).toFixed(2)), yMeters: Number((point.y / 100 * size.heightMeters).toFixed(2)) });
const labelFor = (sourceType: "laptop_camera" | "looped_video") => sourceType === "laptop_camera" ? "Laptop Camera" : "Looped video";

function imageDimensions(file: File) { return new Promise<{ width: number; height: number; url: string }>((resolve, reject) => { const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => resolve({ width: image.naturalWidth, height: image.naturalHeight, url }); image.onerror = () => { URL.revokeObjectURL(url); reject(new Error("The reference image could not be decoded.")); }; image.src = url; }); }
function captureFrame(video: HTMLVideoElement, name: string) { return new Promise<File>((resolve, reject) => { if (!video.videoWidth || !video.videoHeight) return reject(new Error("Wait for the video frame to load before capturing it.")); const canvas = document.createElement("canvas"); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height); canvas.toBlob((blob) => blob ? resolve(new File([blob], name, { type: "image/jpeg" })) : reject(new Error("The browser could not create the reference frame.")), "image/jpeg", .9); }); }

function SiteMap({ zones, size, point, onPoint }: { zones: V2Zone[]; size: { widthMeters: number; heightMeters: number }; point: Point; onPoint: (point: Point) => void }) {
  const onClick = (event: MouseEvent<HTMLDivElement>) => { const box = event.currentTarget.getBoundingClientRect(); onPoint({ x: Math.max(0, Math.min(100, (event.clientX - box.left) / box.width * 100)), y: Math.max(0, Math.min(100, (event.clientY - box.top) / box.height * 100)) }); };
  const currentZone = zones.find((zone) => pointInPolygon(point, zone.polygon.map((vertex) => ({ x: vertex.xMeters / size.widthMeters * 100, y: vertex.yMeters / size.heightMeters * 100 }))));
  return <div className="v2-camera-site-map" onClick={onClick} role="application" tabIndex={0} aria-label="Active Site Map. Click inside a Zone to position the Camera."><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{zones.map((zone) => <polygon key={zone.id} points={zone.polygon.map((vertex) => `${vertex.xMeters / size.widthMeters * 100},${vertex.yMeters / size.heightMeters * 100}`).join(" ")} />)}</svg>{zones.map((zone) => <span key={zone.id} style={{ left: `${zone.polygon.reduce((sum, vertex) => sum + vertex.xMeters / size.widthMeters * 100, 0) / zone.polygon.length}%`, top: `${zone.polygon.reduce((sum, vertex) => sum + vertex.yMeters / size.heightMeters * 100, 0) / zone.polygon.length}%` }}>{zone.zoneNameSnapshot}</span>)}<i style={{ left: `${point.x}%`, top: `${point.y}%` }} /><b>{currentZone ? currentZone.zoneNameSnapshot : "Place inside a Zone"}</b></div>;
}

function ZonePlanner({ zones, size, boundary, onPoint, onUndo, onClear }: { zones: V2Zone[]; size: { widthMeters: number; heightMeters: number }; boundary: Point[]; onPoint: (point: Point) => void; onUndo: () => void; onClear: () => void }) {
  const pointFromEvent = (event: MouseEvent<HTMLDivElement>) => {
    const box = event.currentTarget.getBoundingClientRect();
    onPoint({ x: Math.max(0, Math.min(100, (event.clientX - box.left) / box.width * 100)), y: Math.max(0, Math.min(100, (event.clientY - box.top) / box.height * 100)) });
  };
  return <div className="v2-camera-zone-planner" onClick={pointFromEvent} role="application" tabIndex={0} aria-label="Active Site Map. Click to draw a new Zone boundary.">
    <svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
      {zones.map((zone) => <polygon className="existing" key={zone.id} points={zone.polygon.map((vertex) => `${vertex.xMeters / size.widthMeters * 100},${vertex.yMeters / size.heightMeters * 100}`).join(" ")} />)}
      {boundary.length >= 3 && <polygon className="draft" points={boundary.map((point) => `${point.x},${point.y}`).join(" ")} />}
      {boundary.length >= 2 && <polyline className="draft-line" points={boundary.map((point) => `${point.x},${point.y}`).join(" ")} />}
    </svg>
    {zones.map((zone) => <span className="existing-label" key={zone.id} style={{ left: `${zone.polygon.reduce((sum, vertex) => sum + vertex.xMeters / size.widthMeters * 100, 0) / zone.polygon.length}%`, top: `${zone.polygon.reduce((sum, vertex) => sum + vertex.yMeters / size.heightMeters * 100, 0) / zone.polygon.length}%` }}>{zone.zoneNameSnapshot}</span>)}
    {boundary.map((point, index) => <i className={index === boundary.length - 1 ? "latest" : ""} style={{ left: `${point.x}%`, top: `${point.y}%` }} key={`${point.x}-${point.y}-${index}`} aria-hidden="true" />)}
    <div className="v2-camera-zone-tools"><span>{boundary.length} point{boundary.length === 1 ? "" : "s"}</span><button type="button" onClick={(event) => { event.stopPropagation(); onUndo(); }} disabled={!boundary.length}>Undo</button><button type="button" onClick={(event) => { event.stopPropagation(); onClear(); }} disabled={!boundary.length}>Clear</button></div>
    <p>Click to outline the new Zone · at least 3 points</p>
  </div>;
}

function PlotCanvas({ imageUrl, width, height, floor, bins, mode, pending, onPoint }: { imageUrl: string; width: number; height: number; floor: Point[]; bins: V2RegisteredBin[]; mode: "floor" | "bin"; pending: Point[]; onPoint: (point: Point) => void }) {
  const click = (event: MouseEvent<HTMLDivElement>) => { const box = event.currentTarget.getBoundingClientRect(); onPoint({ x: Math.max(0, Math.min(1, (event.clientX - box.left) / box.width)), y: Math.max(0, Math.min(1, (event.clientY - box.top) / box.height)) }); };
  const polygon = (points: Point[]) => points.map((point) => `${point.x * 100},${point.y * 100}`).join(" ");
  return <div className="v2-camera-plot" style={{ aspectRatio: `${width}/${height}` }} onClick={click} role="application" tabIndex={0} aria-label={`Plot ${mode === "floor" ? "the walkable floor" : "a bin"} on the reference image`}><img src={imageUrl} alt="Camera reference" /><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{polygonValid(floor) && <polygon className="floor" points={polygon(floor)} />}{bins.map((bin) => <polygon className="bin" points={polygon(bin.binPolygon)} key={bin.binId} />)}{pending.length > 1 && <polyline className={`pending ${mode}`} points={polygon(pending)} />}{pending.map((point, index) => <circle className={`pending ${mode}`} cx={point.x * 100} cy={point.y * 100} r=".85" key={`${point.x}-${point.y}-${index}`} />)}</svg><span>Click to add a point · Finish after at least 3 points</span></div>;
}

export function V2CameraCreationPage({ canCreateCamera = true, onClose }: { canCreateCamera?: boolean; onClose: () => void }) {
  const requestedCameraId = new URLSearchParams(location.hash.split("?")[1] ?? "").get("cameraId"); const [kind, setKind] = useState<"create" | "reconfigure">(requestedCameraId ? "reconfigure" : "create"); const [step, setStep] = useState<Step>("location"); const [siteMap, setSiteMap] = useState<V2OperationsReadModel["siteMap"]>(); const [zones, setZones] = useState<V2Zone[]>([]); const [mapSize, setMapSize] = useState({ widthMeters: 1, heightMeters: 1 }); const [cameraCount, setCameraCount] = useState(0); const [name, setName] = useState("Camera 1"); const [description, setDescription] = useState(""); const [sourceType, setSourceType] = useState<"laptop_camera" | "looped_video">("laptop_camera"); const [placement, setPlacement] = useState<Point>({ x: 50, y: 50 }); const [zoneMode, setZoneMode] = useState<"existing" | "new">("existing"); const [newZoneName, setNewZoneName] = useState(""); const [newZoneBoundary, setNewZoneBoundary] = useState<Point[]>([]); const [mapDraftActive, setMapDraftActive] = useState(false); const [draft, setDraft] = useState<V2CameraDraft>(); const [reference, setReference] = useState<{ file: File; url: string; width: number; height: number }>(); const [videoFile, setVideoFile] = useState<File>(); const [videoUrl, setVideoUrl] = useState<string>(); const [floor, setFloor] = useState<Point[]>([]); const [bins, setBins] = useState<V2RegisteredBin[]>([]); const [pending, setPending] = useState<Point[]>([]); const [mode, setMode] = useState<"floor" | "bin">("floor"); const [binName, setBinName] = useState("Bin 1"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [note, setNote] = useState(""); const webcam = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | undefined>(undefined); const video = useRef<HTMLVideoElement>(null);
  useEffect(() => { void getV2OperationsReadModel().then((model) => { setSiteMap(model.siteMap); setZones(model.siteMap.zones); setMapSize(model.siteMap.revision); setCameraCount(model.cameras.length); const existing = requestedCameraId ? model.cameras.find((camera) => camera.id === requestedCameraId) : undefined; if (existing) { setKind("reconfigure"); setName(existing.name); setSourceType(existing.sourceType); if (existing.placement) setPlacement({ x: existing.placement.point.xMeters / model.siteMap.revision.widthMeters * 100, y: existing.placement.point.yMeters / model.siteMap.revision.heightMeters * 100 }); } else { setSourceType(model.cameras.length === 0 ? "laptop_camera" : "looped_video"); setName(`Camera ${model.cameras.length + 1}`); const first = model.siteMap.zones[0]; if (first) setPlacement({ x: first.polygon.reduce((sum, point) => sum + point.xMeters / model.siteMap.revision.widthMeters * 100, 0) / first.polygon.length, y: first.polygon.reduce((sum, point) => sum + point.yMeters / model.siteMap.revision.heightMeters * 100, 0) / first.polygon.length }); } }).catch((reason) => setError(reason instanceof Error ? reason.message : "Camera Creation data could not be loaded.")); return () => stream.current?.getTracks().forEach((track) => track.stop()); }, [requestedCameraId]);
  const placementZone = useMemo(() => zones.find((zone) => pointInPolygon(placement, zone.polygon.map((vertex) => ({ x: vertex.xMeters / mapSize.widthMeters * 100, y: vertex.yMeters / mapSize.heightMeters * 100 })))), [mapSize, placement, zones]);
  const publishNewZone = async () => {
    if (!canCreateCamera) { setError("Root Supervisor access is required to create a new Zone."); return; }
    if (!siteMap || newZoneName.trim().length < 2 || !polygonValid(newZoneBoundary)) { setError("Enter a Zone name and plot at least three points for its boundary."); return; }
    const zoneId = `zone-${globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
    const newZone = { zoneId, zoneNameSnapshot: newZoneName.trim(), polygon: newZoneBoundary.map((point) => toMapPoint(point, mapSize)) };
    setBusy(true); setError("");
    try {
      setMapDraftActive(true);
      await saveV2SiteMapDraft({ baseRevisionId: siteMap.activeRevisionId, widthMeters: siteMap.revision.widthMeters, heightMeters: siteMap.revision.heightMeters, gridSizeMeters: siteMap.revision.gridSizeMeters, backgroundMediaId: siteMap.revision.backgroundMediaId ?? null, backgroundTransform: siteMap.revision.backgroundTransform ?? null, zones: [...zones.map((zone) => ({ zoneId: zone.zoneId, zoneNameSnapshot: zone.zoneNameSnapshot, polygon: zone.polygon })), newZone], cameraPlacements: siteMap.cameraPlacements.map((item) => ({ id: item.cameraId, point: item.point })), cleanerStations: siteMap.cleanerStations.map((item) => ({ id: item.cleanerId, point: item.point })) });
      const validation = await validateV2SiteMapDraft();
      if (!validation.valid) { setError(`Zone validation failed: ${validation.errors.join(", ")}`); return; }
      const published = await publishV2SiteMapDraft();
      setSiteMap(published.map); setZones(published.map.zones); setMapSize(published.map.revision); setPlacement({ x: newZoneBoundary.reduce((sum, point) => sum + point.x, 0) / newZoneBoundary.length, y: newZoneBoundary.reduce((sum, point) => sum + point.y, 0) / newZoneBoundary.length }); setZoneMode("existing"); setNewZoneBoundary([]); setNewZoneName(""); setMapDraftActive(false); setNote(`${newZone.zoneNameSnapshot} is published. Place the Camera inside it, then start the Camera Draft.`);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "The new Zone could not be published."); } finally { setBusy(false); }
  };
  const draftStart = async () => { if (kind === "create" && !canCreateCamera) { setError("Root Supervisor access is required to create a new Camera. Open an existing Camera to re-register it."); return; } if (!name.trim() || kind === "create" && !placementZone) { setError("Name the Camera and place a new Camera inside one active Zone."); return; } setBusy(true); setError(""); try { const result = await startV2CameraDraft({ kind, ...(kind === "reconfigure" && requestedCameraId ? { cameraId: requestedCameraId } : {}), name: name.trim(), description: description.trim() || null, sourceType, placement: kind === "create" ? { point: toMapPoint(placement, mapSize) } : null }); setDraft(result.draft); setStep("source"); setNote(kind === "create" ? "Camera Draft started. It is not operational until validation and publication." : "Replacement Draft started. The existing Camera remains operational until publication."); } catch (reason) { setError(reason instanceof Error ? reason.message : "The Camera Draft could not be started."); } finally { setBusy(false); } };
  const uploadReference = async (file: File) => { if (!draft) return; setBusy(true); setError(""); try { const [dimensions] = await Promise.all([imageDimensions(file), uploadV2CameraDraftReference(draft.id, file)]); setReference({ file, url: dimensions.url, width: dimensions.width, height: dimensions.height }); setNote("Reference saved. Plot the walkable floor next."); setStep("plot"); } catch (reason) { setError(reason instanceof Error ? reason.message : "The reference could not be stored."); } finally { setBusy(false); } };
  const chooseVideo = async (file: File) => { if (!draft) return; setBusy(true); setError(""); try { const response = await uploadV2CameraDraftSourceVideo(draft.id, file); const url = URL.createObjectURL(file); setVideoFile(file); setVideoUrl(url); setNote(`Looped source saved (${Math.round(response.source.durationSeconds)} seconds). Pause at a clean frame and capture it as the reference.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "The looped video could not be stored."); } finally { setBusy(false); } };
  const startWebcam = async () => { try { stream.current?.getTracks().forEach((track) => track.stop()); stream.current = await navigator.mediaDevices.getUserMedia({ video: true, audio: false }); if (webcam.current) webcam.current.srcObject = stream.current; } catch (reason) { setError(reason instanceof Error ? reason.message : "The laptop Camera could not be opened."); } };
  const captureWebcam = async () => { if (!webcam.current) return; try { await uploadReference(await captureFrame(webcam.current, "laptop-reference.jpg")); stream.current?.getTracks().forEach((track) => track.stop()); } catch (reason) { setError(reason instanceof Error ? reason.message : "The laptop reference could not be captured."); } };
  const addPoint = (point: Point) => setPending((points) => [...points, point]);
  const finishPolygon = () => { if (!polygonValid(pending)) { setError("Plot at least three distinct points before finishing the polygon."); return; } if (mode === "floor") { setFloor(pending); setMode("bin"); setBinName(`Bin ${bins.length + 1}`); setNote("Floor saved. Add any visible physical bins, or continue to review."); } else { setBins((items) => [...items, { binId: `bin-${items.length + 1}`, displayName: binName.trim() || `Bin ${items.length + 1}`, binType: "unknown", binPolygon: pending }]); setBinName(`Bin ${bins.length + 2}`); setNote("Bin saved. Add another bin or continue to review."); } setPending([]); setError(""); };
  const saveAndValidate = async () => { if (!draft || !reference || !polygonValid(floor)) { setError("Upload a reference and complete the walkable-floor polygon first."); return; } setBusy(true); setError(""); try { await saveV2CameraDraftRegistration(draft.id, { sourceWidth: reference.width, sourceHeight: reference.height, walkableFloorPolygon: floor, bins }); const validation = await validateV2CameraDraft(draft.id); if (!validation.valid) { setError(`Draft validation failed: ${validation.errors.join(", ")}`); return; } setStep("review"); setNote("Draft is valid and ready to publish."); } catch (reason) { setError(reason instanceof Error ? reason.message : "The registration could not be validated."); } finally { setBusy(false); } };
  const publish = async () => { if (!draft) return; setBusy(true); setError(""); try { const result = await publishV2CameraDraft(draft.id); setNote("Camera published successfully."); location.hash = `/cameras?cameraId=${encodeURIComponent(result.result.cameraId)}&created=1`; } catch (reason) { setError(reason instanceof Error ? reason.message : "The Camera could not be published."); } finally { setBusy(false); } };
  const close = () => { stream.current?.getTracks().forEach((track) => track.stop()); if (mapDraftActive) void deleteV2SiteMapDraft().catch(() => undefined); if (reference?.url) URL.revokeObjectURL(reference.url); if (videoUrl) URL.revokeObjectURL(videoUrl); onClose(); };
  const sourceReady = Boolean(reference); const floorReady = polygonValid(floor); const plotReady = sourceReady && floorReady; const reviewReady = plotReady;
  return <section className="v2-camera-creation"><header><div><span>CAMERA CREATION</span><h1>{kind === "create" ? "Register a new view." : "Re-register this view."}</h1><p>Place it on the Site Map, establish a clean reference, plot its detection regions, then publish one validated Camera.</p></div><button type="button" onClick={close} disabled={busy}>Close</button></header><nav className="v2-camera-steps">{steps.map((item) => <button type="button" key={item.id} className={step === item.id ? "active" : item.id === "source" && sourceReady || item.id === "plot" && floorReady || item.id === "review" && reviewReady ? "ready" : ""} onClick={() => { if (item.id === "location" || item.id === "source" && draft || item.id === "plot" && sourceReady || item.id === "review" && reviewReady) setStep(item.id); }}><b>{item.number}</b><span>{item.label}</span></button>)}</nav>{error && <p className="v2-camera-error" role="alert">{error}</p>}{note && <p className="v2-camera-note">{note}</p>}
    {step === "location" && <section className="v2-camera-stage location"><div className="v2-camera-map-panel"><header><div><span>ACTIVE SITE MAP</span><strong>{placementZone?.zoneNameSnapshot ?? "Place the Camera inside a Zone"}</strong></div>{canCreateCamera && kind === "create" && <div className="v2-camera-zone-mode" role="group" aria-label="Choose Zone setup"><button type="button" className={zoneMode === "existing" ? "active" : ""} onClick={() => setZoneMode("existing")}>Existing Zone</button><button type="button" className={zoneMode === "new" ? "active" : ""} onClick={() => setZoneMode("new")}>Create Zone</button></div>}</header>{zoneMode === "new" ? <><label className="v2-camera-new-zone-name">New Zone name<input value={newZoneName} onChange={(event) => setNewZoneName(event.target.value)} placeholder="North concourse" /></label><ZonePlanner zones={zones} size={mapSize} boundary={newZoneBoundary} onPoint={(point) => setNewZoneBoundary((current) => [...current, point])} onUndo={() => setNewZoneBoundary((current) => current.slice(0, -1))} onClear={() => setNewZoneBoundary([])} /><button type="button" className="v2-camera-publish-zone" onClick={() => void publishNewZone()} disabled={busy || newZoneName.trim().length < 2 || !polygonValid(newZoneBoundary)}>{busy ? "Publishing Zone…" : "Publish Zone & continue →"}</button></> : <SiteMap zones={zones} size={mapSize} point={placement} onPoint={setPlacement} />}</div><form onSubmit={(event) => { event.preventDefault(); void draftStart(); }}><label>Camera name<input value={name} onChange={(event) => setName(event.target.value)} minLength={2} required /></label><label>Description <small>(optional)</small><textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><fieldset><legend>Source</legend><label><input type="radio" checked={sourceType === "laptop_camera"} onChange={() => setSourceType("laptop_camera")} disabled={cameraCount > 0} />Laptop Camera</label><label><input type="radio" checked={sourceType === "looped_video"} onChange={() => setSourceType("looped_video")} disabled={cameraCount === 0} />Looped video</label><small>{cameraCount === 0 ? "The first Camera is required to use this laptop's Camera." : "Later prototype Cameras use looped video and publish with monitoring disabled until a Supervisor enables a demonstration."}</small></fieldset><dl><div><dt>ZONE</dt><dd>{placementZone?.zoneNameSnapshot ?? "Not selected"}</dd></div><div><dt>MAP POINT</dt><dd>X {toMapPoint(placement, mapSize).xMeters} m · Y {toMapPoint(placement, mapSize).yMeters} m</dd></div></dl><button type="submit" disabled={busy || !placementZone || zoneMode === "new"}>{busy ? "Starting…" : "Start Camera Draft →"}</button></form></section>}
    {step === "source" && <section className="v2-camera-stage source"><div><span>CAMERA SOURCE</span><h2>{labelFor(sourceType)}</h2><p>{sourceType === "laptop_camera" ? "Open the laptop Camera, choose a clean frame, and capture the configuration reference." : "Upload the looping demonstration video, then capture a clean reference frame from it."}</p>{sourceType === "laptop_camera" ? <><video ref={webcam} autoPlay muted playsInline className="v2-camera-video" /><div className="v2-camera-actions"><button type="button" onClick={() => void startWebcam()}>Open laptop Camera</button><button type="button" onClick={() => void captureWebcam()} disabled={busy}>Capture clean reference</button></div></> : <><label className="v2-camera-upload">Choose looped video<input type="file" accept="video/mp4,video/quicktime,video/webm" onChange={(event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) void chooseVideo(file); }} /></label>{videoUrl && <><video ref={video} className="v2-camera-video" src={videoUrl} controls playsInline /><button type="button" disabled={busy || !videoFile} onClick={() => { if (video.current) void captureFrame(video.current, "video-reference.jpg").then(uploadReference).catch((reason) => setError(reason instanceof Error ? reason.message : "The video frame could not be captured.")); }}>Capture current frame as reference</button></>}</>}</div><aside>{reference ? <><img src={reference.url} alt="Saved Camera reference" /><b>Reference ready</b><span>{reference.width} × {reference.height}</span><button type="button" onClick={() => setStep("plot")}>Plot detection regions →</button></> : <p>Reference image required before plotting.</p>}</aside></section>}
    {step === "plot" && reference && <section className="v2-camera-stage plot"><header><div><span>REGISTRATION PLOTS</span><h2>{mode === "floor" ? "Mark the walkable floor." : "Mark visible physical bins."}</h2><p>{mode === "floor" ? "The model only inspects the floor inside this boundary." : "Bin plotting is optional. Add only bins physically visible in this Camera view."}</p></div><div className="v2-camera-plot-controls"><button type="button" className={mode === "floor" ? "active" : ""} onClick={() => { setMode("floor"); setPending([]); }}>Floor</button><button type="button" className={mode === "bin" ? "active" : ""} onClick={() => { setMode("bin"); setPending([]); }}>Bins ({bins.length})</button><button type="button" onClick={() => setPending((points) => points.slice(0, -1))} disabled={!pending.length}>Undo</button><button type="button" onClick={() => setPending([])} disabled={!pending.length}>Clear</button></div></header>{mode === "bin" && <label className="v2-camera-bin-name">Bin display name<input value={binName} onChange={(event) => setBinName(event.target.value)} /></label>}<PlotCanvas imageUrl={reference.url} width={reference.width} height={reference.height} floor={floor} bins={bins} mode={mode} pending={pending} onPoint={addPoint} /><footer><span>{mode === "floor" && floorReady ? "Floor polygon saved." : `${pending.length} point${pending.length === 1 ? "" : "s"} plotted`}</span><div><button type="button" onClick={finishPolygon} disabled={!pending.length}>Finish polygon</button><button type="button" onClick={() => void saveAndValidate()} disabled={busy || !floorReady}>{busy ? "Validating…" : "Validate registration →"}</button></div></footer></section>}
    {step === "review" && <section className="v2-camera-stage review"><div><span>VALIDATED DRAFT</span><h2>Ready to publish.</h2><p>Publishing atomically creates the operational Camera, its placement, source revision, and Registration. {sourceType === "looped_video" ? "Monitoring stays disabled until a Supervisor enables the demo." : "Laptop monitoring is enabled after publication."}</p><dl><div><dt>CAMERA</dt><dd>{name}</dd></div><div><dt>ZONE</dt><dd>{placementZone?.zoneNameSnapshot}</dd></div><div><dt>SOURCE</dt><dd>{labelFor(sourceType)}</dd></div><div><dt>BINS</dt><dd>{bins.length}</dd></div></dl><button type="button" onClick={() => void publish()} disabled={busy}>{busy ? "Publishing…" : "Publish Camera →"}</button></div>{reference && <PlotCanvas imageUrl={reference.url} width={reference.width} height={reference.height} floor={floor} bins={bins} mode="floor" pending={[]} onPoint={() => undefined} />}</section>}
  </section>;
}
