import { useEffect, useMemo, useRef, useState, type ChangeEvent, type MouseEvent } from "react";
import { deleteV2CameraDraft, getV2OperationsReadModel, publishV2CameraDraft, saveV2CameraDraftRegistration, startV2CameraDraft, uploadV2CameraDraftReference, uploadV2CameraDraftSourceVideo, validateV2CameraDraft, type V2CameraDraft, type V2OperationsReadModel, type V2Point, type V2RegisteredBin, type V2Zone } from "../services/v2/operations";
import "./v2-camera-creation.css";
import "./v2-camera-zone-planner.css";

type Point = { x: number; y: number };
type Step = "location" | "source" | "plot" | "review";
const steps: Array<{ id: Step; number: string; label: string }> = [{ id: "location", number: "01", label: "Place Camera" }, { id: "source", number: "02", label: "Reference" }, { id: "plot", number: "03", label: "Plot regions" }, { id: "review", number: "04", label: "Validate & publish" }];

const pointInPolygon = (point: Point, polygon: Point[]) => { let inside = false; for (let index = 0, previous = polygon.length - 1; index < polygon.length; previous = index++) { const a = polygon[index]; const b = polygon[previous]; if ((a.y > point.y) !== (b.y > point.y) && point.x < (b.x - a.x) * (point.y - a.y) / (b.y - a.y) + a.x) inside = !inside; } return inside; };
const polygonValid = (points: Point[]) => points.length >= 3 && Math.abs(points.reduce((sum, point, index) => { const next = points[(index + 1) % points.length]; return sum + point.x * next.y - next.x * point.y; }, 0)) > 0.0001;
const toMapPoint = (point: Point, size: { widthMeters: number; heightMeters: number }): V2Point => ({ xMeters: Number((point.x / 100 * size.widthMeters).toFixed(2)), yMeters: Number((point.y / 100 * size.heightMeters).toFixed(2)) });
const labelFor = (sourceType: "laptop_camera" | "looped_video") => sourceType === "laptop_camera" ? "Laptop Camera" : "Looped video";

function imageDimensions(file: File) { return new Promise<{ width: number; height: number; url: string }>((resolve, reject) => { const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => resolve({ width: image.naturalWidth, height: image.naturalHeight, url }); image.onerror = () => { URL.revokeObjectURL(url); reject(new Error("The reference image could not be decoded.")); }; image.src = url; }); }
function captureFrame(video: HTMLVideoElement, name: string) { return new Promise<File>((resolve, reject) => { if (!video.videoWidth || !video.videoHeight) return reject(new Error("Wait for the video frame to load before capturing it.")); const canvas = document.createElement("canvas"); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height); canvas.toBlob((blob) => blob ? resolve(new File([blob], name, { type: "image/jpeg" })) : reject(new Error("The browser could not create the reference frame.")), "image/jpeg", .9); }); }

export function zoneAtPoint(point: Point, zones: V2Zone[], size: { widthMeters: number; heightMeters: number }) {
  return zones.find((zone) => pointInPolygon(point, zone.polygon.map((vertex) => ({ x: vertex.xMeters / size.widthMeters * 100, y: vertex.yMeters / size.heightMeters * 100 }))));
}

function SiteMap({ zones, size, point, selectedZoneId, selectingZone, onSelectZone, onPoint }: { zones: V2Zone[]; size: { widthMeters: number; heightMeters: number }; point: Point | null; selectedZoneId: string; selectingZone: boolean; onSelectZone: (zoneId: string) => void; onPoint: (point: Point) => void }) {
  const onClick = (event: MouseEvent<HTMLDivElement>) => {
    const box = event.currentTarget.getBoundingClientRect();
    const nextPoint = { x: Math.max(0, Math.min(100, (event.clientX - box.left) / box.width * 100)), y: Math.max(0, Math.min(100, (event.clientY - box.top) / box.height * 100)) };
    const zone = zoneAtPoint(nextPoint, zones, size);
    if (!zone) return;
    if (selectingZone) { onSelectZone(zone.zoneId); return; }
    onPoint(nextPoint);
  };
  return <div className="camera-zone-map v2-camera-site-map" onClick={onClick} role="application" tabIndex={0} aria-label={selectingZone ? "Active Site Map. Click a Zone to select it for this Camera." : "Active Site Map. Click inside the selected Zone to position the Camera."}><div className="camera-zone-map-art" /><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{zones.map((zone) => <polygon className={selectedZoneId === zone.zoneId ? "selected" : ""} key={zone.id} points={zone.polygon.map((vertex) => `${vertex.xMeters / size.widthMeters * 100},${vertex.yMeters / size.heightMeters * 100}`).join(" ")} />)}</svg>{zones.map((zone) => <span key={zone.id} style={{ left: `${zone.polygon.reduce((sum, vertex) => sum + vertex.xMeters / size.widthMeters * 100, 0) / zone.polygon.length}%`, top: `${zone.polygon.reduce((sum, vertex) => sum + vertex.yMeters / size.heightMeters * 100, 0) / zone.polygon.length}%` }}>{zone.zoneNameSnapshot}</span>)}{point && <i className="camera-location-pin" style={{ left: `${point.x}%`, top: `${point.y}%` }} />}<p className="camera-zone-map-instruction">{selectingZone ? "Click a Zone to select it, or use the Zone list" : "Click inside the selected Zone to place the Camera"}</p></div>;
}

function ZonePlanner({ zones, size, boundary, onPoint, onUndo, onClear }: { zones: V2Zone[]; size: { widthMeters: number; heightMeters: number }; boundary: Point[]; onPoint: (point: Point) => void; onUndo: () => void; onClear: () => void }) {
  const pointFromEvent = (event: MouseEvent<HTMLDivElement>) => {
    const box = event.currentTarget.getBoundingClientRect();
    onPoint({ x: Math.max(0, Math.min(100, (event.clientX - box.left) / box.width * 100)), y: Math.max(0, Math.min(100, (event.clientY - box.top) / box.height * 100)) });
  };
  return <div className="camera-zone-map v2-camera-zone-planner" onClick={pointFromEvent} role="application" tabIndex={0} aria-label="Active Site Map. Click to draw a new Zone boundary.">
    <div className="camera-zone-map-art" />
    <svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
      {zones.map((zone) => <polygon className="existing" key={zone.id} points={zone.polygon.map((vertex) => `${vertex.xMeters / size.widthMeters * 100},${vertex.yMeters / size.heightMeters * 100}`).join(" ")} />)}
      {boundary.length >= 3 && <polygon className="draft" points={boundary.map((point) => `${point.x},${point.y}`).join(" ")} />}
      {boundary.length >= 2 && <polyline className="draft-line" points={boundary.map((point) => `${point.x},${point.y}`).join(" ")} />}
    </svg>
    {zones.map((zone) => <span className="existing-label" key={zone.id} style={{ left: `${zone.polygon.reduce((sum, vertex) => sum + vertex.xMeters / size.widthMeters * 100, 0) / zone.polygon.length}%`, top: `${zone.polygon.reduce((sum, vertex) => sum + vertex.yMeters / size.heightMeters * 100, 0) / zone.polygon.length}%` }}>{zone.zoneNameSnapshot}</span>)}
    {boundary.map((point, index) => <i className={index === boundary.length - 1 ? "latest" : ""} style={{ left: `${point.x}%`, top: `${point.y}%` }} key={`${point.x}-${point.y}-${index}`} aria-hidden="true" />)}
    <div className="v2-camera-zone-tools"><span>{boundary.length} point{boundary.length === 1 ? "" : "s"}</span><button type="button" onClick={(event) => { event.stopPropagation(); onUndo(); }} disabled={!boundary.length}>Undo</button><button type="button" onClick={(event) => { event.stopPropagation(); onClear(); }} disabled={!boundary.length}>Clear</button></div>
    <p>Click to outline the new Zone · at least 3 points</p>
  </div>;
}

function PlotCanvas({ imageUrl, width, height, floor, bins, mode, pending, onPoint }: { imageUrl: string; width: number; height: number; floor: Point[]; bins: V2RegisteredBin[]; mode: "floor" | "bin"; pending: Point[]; onPoint: (point: Point) => void }) {
  const click = (event: MouseEvent<HTMLDivElement>) => { const box = event.currentTarget.getBoundingClientRect(); onPoint({ x: Math.max(0, Math.min(1, (event.clientX - box.left) / box.width)), y: Math.max(0, Math.min(1, (event.clientY - box.top) / box.height)) }); };
  const polygon = (points: Point[]) => points.map((point) => `${point.x * 100},${point.y * 100}`).join(" ");
  return <div className="v2-camera-plot" style={{ aspectRatio: `${width}/${height}` }} onClick={click} role="application" tabIndex={0} aria-label={`Plot ${mode === "floor" ? "the walkable floor" : "a bin"} on the reference image`}><img src={imageUrl} alt="Camera reference" /><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{polygonValid(floor) && <polygon className="floor" points={polygon(floor)} />}{bins.map((bin) => <polygon className="bin" points={polygon(bin.binPolygon)} key={bin.binId} />)}{pending.length > 1 && <polyline className={`pending ${mode}`} points={polygon(pending)} />}{pending.map((point, index) => <circle className={`pending ${mode}`} cx={point.x * 100} cy={point.y * 100} r=".85" key={`${point.x}-${point.y}-${index}`} />)}</svg><span>Click to add a point · Finish after at least 3 points</span></div>;
}

export function V2CameraCreationPage({ canCreateCamera = true, onClose, onPublished }: { canCreateCamera?: boolean; onClose: () => void; onPublished?: (cameraId: string) => void | Promise<void> }) {
  const requestedCameraId = new URLSearchParams(location.hash.split("?")[1] ?? "").get("cameraId"); const [kind, setKind] = useState<"create" | "reconfigure">(requestedCameraId ? "reconfigure" : "create"); const [step, setStep] = useState<Step>("location"); const [siteMap, setSiteMap] = useState<V2OperationsReadModel["siteMap"]>(); const [zones, setZones] = useState<V2Zone[]>([]); const [mapSize, setMapSize] = useState({ widthMeters: 1, heightMeters: 1 }); const [cameraCount, setCameraCount] = useState(0); const [name, setName] = useState("Camera 1"); const [description, setDescription] = useState(""); const [sourceType, setSourceType] = useState<"laptop_camera" | "looped_video">("laptop_camera"); const [placement, setPlacement] = useState<Point | null>(null); const [selectedZoneId, setSelectedZoneId] = useState(""); const [locationPlotting, setLocationPlotting] = useState(false); const [zoneMode, setZoneMode] = useState<"existing" | "new">("existing"); const [newZoneName, setNewZoneName] = useState(""); const [newZoneBoundary, setNewZoneBoundary] = useState<Point[]>([]); const [provisionalZone, setProvisionalZone] = useState<V2Zone>(); const [draft, setDraft] = useState<V2CameraDraft>(); const [reference, setReference] = useState<{ file: File; url: string; width: number; height: number }>(); const [videoFile, setVideoFile] = useState<File>(); const [videoUrl, setVideoUrl] = useState<string>(); const [floor, setFloor] = useState<Point[]>([]); const [bins, setBins] = useState<V2RegisteredBin[]>([]); const [pending, setPending] = useState<Point[]>([]); const [mode, setMode] = useState<"floor" | "bin">("floor"); const [binName, setBinName] = useState("Bin 1"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [note, setNote] = useState(""); const webcam = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | undefined>(undefined); const video = useRef<HTMLVideoElement>(null);
  useEffect(() => { void getV2OperationsReadModel().then((model) => { setSiteMap(model.siteMap); setZones(model.siteMap.zones); setMapSize(model.siteMap.revision); setCameraCount(model.cameras.length); const existing = requestedCameraId ? model.cameras.find((camera) => camera.id === requestedCameraId) : undefined; if (existing) { setKind("reconfigure"); setName(existing.name); setSourceType(existing.sourceType); if (existing.placement) { setSelectedZoneId(existing.placement.zoneId); setPlacement({ x: existing.placement.point.xMeters / model.siteMap.revision.widthMeters * 100, y: existing.placement.point.yMeters / model.siteMap.revision.heightMeters * 100 }); setLocationPlotting(true); } } else { setSourceType(model.cameras.length === 0 ? "laptop_camera" : "looped_video"); setName(`Camera ${model.cameras.length + 1}`); } }).catch((reason) => setError(reason instanceof Error ? reason.message : "Camera Creation data could not be loaded.")); return () => stream.current?.getTracks().forEach((track) => track.stop()); }, [requestedCameraId]);
  const availableZones = useMemo(() => provisionalZone ? [...zones, provisionalZone] : zones, [provisionalZone, zones]);
  const placementZone = useMemo(() => placement ? availableZones.find((zone) => pointInPolygon(placement, zone.polygon.map((vertex) => ({ x: vertex.xMeters / mapSize.widthMeters * 100, y: vertex.yMeters / mapSize.heightMeters * 100 })))) : undefined, [availableZones, mapSize, placement]);
  const saveProvisionalZone = () => {
    if (!canCreateCamera) { setError("Root Supervisor access is required to create a new Zone."); return; }
    if (!siteMap || newZoneName.trim().length < 2 || !polygonValid(newZoneBoundary)) { setError("Enter a Zone name and plot at least three points for its boundary."); return; }
    const zoneId = `zone-${globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
    const newZone = { id: zoneId, zoneId, zoneNameSnapshot: newZoneName.trim(), polygon: newZoneBoundary.map((point) => toMapPoint(point, mapSize)) };
    setProvisionalZone(newZone); setSelectedZoneId(zoneId); setPlacement(null); setLocationPlotting(true); setZoneMode("existing"); setError(""); setNote(`${newZone.zoneNameSnapshot} is provisional. It will only be created when the Camera is published on Page 4.`);
  };
  const draftStart = async () => { if (kind === "create" && !canCreateCamera) { setError("Root Supervisor access is required to create a new Camera. Open an existing Camera to re-register it."); return; } if (!name.trim() || kind === "create" && (!placement || !placementZone || placementZone.zoneId !== selectedZoneId)) { setError("Name the Camera and place it inside the selected Zone."); return; } setBusy(true); setError(""); try { const result = await startV2CameraDraft({ kind, ...(kind === "reconfigure" && requestedCameraId ? { cameraId: requestedCameraId } : {}), name: name.trim(), description: description.trim() || null, sourceType, placement: kind === "create" && placement ? { point: toMapPoint(placement, mapSize) } : null, provisionalZone: provisionalZone ? { zoneId: provisionalZone.zoneId, zoneNameSnapshot: provisionalZone.zoneNameSnapshot, polygon: provisionalZone.polygon } : null }); setDraft(result.draft); setStep("source"); setNote(kind === "create" ? "Camera Draft started. Nothing becomes operational until Page 4." : "Replacement Draft started. The existing Camera remains operational until publication."); } catch (reason) { setError(reason instanceof Error ? reason.message : "The Camera Draft could not be started."); } finally { setBusy(false); } };
  const uploadReference = async (file: File) => { if (!draft) return; setBusy(true); setError(""); try { const [dimensions] = await Promise.all([imageDimensions(file), uploadV2CameraDraftReference(draft.id, file)]); if (reference?.url) URL.revokeObjectURL(reference.url); setReference({ file, url: dimensions.url, width: dimensions.width, height: dimensions.height }); setNote("Reference saved. Continue when this is the frame you want to use for registration."); } catch (reason) { setError(reason instanceof Error ? reason.message : "The reference could not be stored."); } finally { setBusy(false); } };
  const chooseVideo = async (file: File) => { if (!draft) return; setBusy(true); setError(""); try { const response = await uploadV2CameraDraftSourceVideo(draft.id, file); const url = URL.createObjectURL(file); setVideoFile(file); setVideoUrl(url); setNote(`Looped source saved (${Math.round(response.source.durationSeconds)} seconds). Pause at a clean frame and capture it as the reference.`); } catch (reason) { setError(reason instanceof Error ? reason.message : "The looped video could not be stored."); } finally { setBusy(false); } };
  const startWebcam = async () => { try { stream.current?.getTracks().forEach((track) => track.stop()); stream.current = await navigator.mediaDevices.getUserMedia({ video: true, audio: false }); if (webcam.current) webcam.current.srcObject = stream.current; } catch (reason) { setError(reason instanceof Error ? reason.message : "The laptop Camera could not be opened."); } };
  const captureWebcam = async () => { if (!webcam.current) return; try { await uploadReference(await captureFrame(webcam.current, "laptop-reference.jpg")); stream.current?.getTracks().forEach((track) => track.stop()); } catch (reason) { setError(reason instanceof Error ? reason.message : "The laptop reference could not be captured."); } };
  const addPoint = (point: Point) => setPending((points) => [...points, point]);
  const finishPolygon = () => { if (!polygonValid(pending)) { setError("Plot at least three distinct points before finishing the polygon."); return; } if (mode === "floor") { setFloor(pending); setMode("bin"); setBinName(`Bin ${bins.length + 1}`); setNote("Floor saved. Add any visible physical bins, or continue to review."); } else { setBins((items) => [...items, { binId: `bin-${items.length + 1}`, displayName: binName.trim() || `Bin ${items.length + 1}`, binType: "unknown", binPolygon: pending }]); setBinName(`Bin ${bins.length + 2}`); setNote("Bin saved. Add another bin or continue to review."); } setPending([]); setError(""); };
  const saveAndValidate = async () => { if (!draft || !reference || !polygonValid(floor)) { setError("Upload a reference and complete the walkable-floor polygon first."); return; } setBusy(true); setError(""); try { await saveV2CameraDraftRegistration(draft.id, { sourceWidth: reference.width, sourceHeight: reference.height, walkableFloorPolygon: floor, bins }); const validation = await validateV2CameraDraft(draft.id); if (!validation.valid) { setError(`Draft validation failed: ${validation.errors.join(", ")}`); return; } setStep("review"); setNote("Draft is valid and ready to publish."); } catch (reason) { setError(reason instanceof Error ? reason.message : "The registration could not be validated."); } finally { setBusy(false); } };
  const publish = async () => { if (!draft) return; setBusy(true); setError(""); try { const result = await publishV2CameraDraft(draft.id); setNote("Camera published successfully."); await onPublished?.(result.result.cameraId); if (!onPublished) location.hash = `/cameras?cameraId=${encodeURIComponent(result.result.cameraId)}&created=1`; } catch (reason) { setError(reason instanceof Error ? reason.message : "The Camera could not be published."); } finally { setBusy(false); } };
  const close = async () => { if (busy) return; setBusy(true); setError(""); try { if (draft) await deleteV2CameraDraft(draft.id); stream.current?.getTracks().forEach((track) => track.stop()); if (reference?.url) URL.revokeObjectURL(reference.url); if (videoUrl) URL.revokeObjectURL(videoUrl); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The unfinished Camera registration could not be cancelled."); } finally { setBusy(false); } };
  const sourceReady = Boolean(reference); const floorReady = polygonValid(floor); const plotReady = sourceReady && floorReady; const reviewReady = plotReady;
  const goBack = () => setStep(step === "review" ? "plot" : step === "plot" ? "source" : "location");
  const next = () => {
    setError("");
    if (step === "location") draft ? setStep("source") : void draftStart();
    else if (step === "source" && reference) setStep("plot");
    else if (step === "plot") void saveAndValidate();
    else if (step === "review") void publish();
  };
  const nextDisabled = busy || step === "location" && !draft && (!locationPlotting || !placement || !placementZone || placementZone.zoneId !== selectedZoneId || !name.trim()) || step === "source" && !sourceReady || step === "plot" && !floorReady || step === "review" && !reviewReady;
  const nextLabel = busy ? step === "location" ? "Saving draft…" : step === "plot" ? "Validating…" : step === "review" ? "Publishing…" : "Saving reference…" : step === "location" ? draft ? "Return to reference →" : "Continue to reference →" : step === "source" ? "Continue to region plotting →" : step === "plot" ? "Continue to validation →" : "Validate & publish →";

  return <div className="camera-modal-scrim camera-registration-scrim" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) close(); }}>
    <section className="camera-add-modal camera-registration-wizard" role="dialog" aria-modal="true" aria-labelledby="camera-registration-title">
      <header><div><span>{kind === "create" ? "NEW CAMERA" : "CAMERA RECONFIGURATION"} · {siteMap?.siteName ?? "ACTIVE SITE"}</span><h2 id="camera-registration-title">{kind === "create" ? "Create a new camera." : `Re-register ${name}.`}</h2><p>Complete all four pages before this Camera becomes operational.</p></div><button type="button" onClick={close} disabled={busy} aria-label="Close camera registration">×</button></header>
      <nav className="camera-registration-progress" aria-label="Camera registration progress">{steps.map((item) => { const currentIndex = steps.findIndex((candidate) => candidate.id === step); const itemIndex = steps.findIndex((candidate) => candidate.id === item.id); const unlocked = itemIndex <= currentIndex || item.id === "source" && Boolean(draft) || item.id === "plot" && sourceReady || item.id === "review" && reviewReady; return <button type="button" key={item.id} className={step === item.id ? "active" : itemIndex < currentIndex ? "complete" : ""} disabled={!unlocked} onClick={() => unlocked && setStep(item.id)}><b>{item.number}</b><span>{item.label}</span></button>; })}</nav>

      {step === "location" && <div className="camera-add-body with-zone-map registration-location-page">
        <section className="camera-modal-section camera-modal-location">
          <span className="camera-modal-step">01 / ZONE & LOCATION</span>
          {canCreateCamera && kind === "create" && <div className="camera-zone-mode" role="group" aria-label="Choose zone setup"><button type="button" disabled={Boolean(draft)} className={zoneMode === "existing" ? "active" : ""} onClick={() => setZoneMode("existing")}><b>Existing zone</b><small>Select a registered area on the map</small></button><button type="button" disabled={Boolean(draft)} className={zoneMode === "new" ? "active" : ""} onClick={() => setZoneMode("new")}><b>Create new zone</b><small>Name and outline a new area</small></button></div>}
          {zoneMode === "existing" ? <label>Cleaning zone<select disabled={Boolean(draft)} value={selectedZoneId} onChange={(event) => { setSelectedZoneId(event.target.value); setPlacement(null); setLocationPlotting(false); setError(""); }}><option value="" disabled>Select a zone</option>{availableZones.map((zone) => <option key={zone.id} value={zone.zoneId}>{zone.zoneNameSnapshot}{zone.zoneId === provisionalZone?.zoneId ? " · new" : ""}</option>)}</select></label> : <><label>New zone name<input disabled={Boolean(draft)} value={newZoneName} onChange={(event) => setNewZoneName(event.target.value)} placeholder="South concourse" minLength={2} /></label><button type="button" className="camera-provisional-zone-action primary" onClick={saveProvisionalZone} disabled={busy || newZoneName.trim().length < 2 || !polygonValid(newZoneBoundary)}>Save Zone & place Camera →</button></>}
          <section className="camera-zone-planner">
            <header><div><span>{zoneMode === "new" ? "ZONE BOUNDARY" : locationPlotting ? "CAMERA LOCATION" : "SELECTED ZONE"}</span><strong>{draft ? "Camera placement saved." : zoneMode === "new" ? polygonValid(newZoneBoundary) ? "New Zone boundary ready." : "Outline the new Zone." : !selectedZoneId ? "Click a Zone on the map or choose one from the list." : !locationPlotting ? availableZones.find((zone) => zone.zoneId === selectedZoneId)?.zoneNameSnapshot : placementZone?.zoneNameSnapshot ?? "Place the Camera inside the selected Zone."}</strong></div><b className={draft || placement && placementZone?.zoneId === selectedZoneId || zoneMode === "new" && polygonValid(newZoneBoundary) ? "ready" : ""}>{draft ? "Saved" : placement && placementZone?.zoneId === selectedZoneId || zoneMode === "new" && polygonValid(newZoneBoundary) ? "Ready" : "Step 1"}</b></header>
            {zoneMode === "new" ? <ZonePlanner zones={zones} size={mapSize} boundary={newZoneBoundary} onPoint={(point) => { if (!draft) setNewZoneBoundary((current) => [...current, point]); }} onUndo={() => setNewZoneBoundary((current) => current.slice(0, -1))} onClear={() => setNewZoneBoundary([])} /> : <SiteMap zones={availableZones} size={mapSize} point={placement} selectedZoneId={selectedZoneId} selectingZone={!locationPlotting} onSelectZone={(zoneId) => { if (draft) return; setSelectedZoneId(zoneId); setPlacement(null); setError(""); }} onPoint={(point) => { if (draft || !locationPlotting) return; const selected = availableZones.find((zone) => zone.zoneId === selectedZoneId); if (!selected || !pointInPolygon(point, selected.polygon.map((vertex) => ({ x: vertex.xMeters / mapSize.widthMeters * 100, y: vertex.yMeters / mapSize.heightMeters * 100 })))) { setError("Place the Camera inside the selected Zone."); return; } setPlacement(point); setError(""); }} />}
            <div className="camera-zone-readout"><div><span>CAMERA COORDINATES</span><strong>{placement ? `X ${toMapPoint(placement, mapSize).xMeters} m` : "Not plotted"}</strong><small>{placement ? `Y ${toMapPoint(placement, mapSize).yMeters} m` : locationPlotting ? "Click the map to place" : "Select the Zone first"}</small></div><div><span>PAGE STATUS</span><strong>{draft ? "Draft placement saved" : placement && placementZone?.zoneId === selectedZoneId ? "Zone and location ready" : zoneMode === "new" && polygonValid(newZoneBoundary) ? "Zone ready to save" : locationPlotting ? "Place the Camera" : "Complete Zone selection"}</strong><small>{placementZone?.zoneNameSnapshot ?? availableZones.find((zone) => zone.zoneId === selectedZoneId)?.zoneNameSnapshot ?? siteMap?.siteName}</small></div></div>
          </section>
        </section>
        {zoneMode === "existing" && !locationPlotting && <div className="camera-location-next existing"><button type="button" className="primary" disabled={!selectedZoneId || Boolean(draft)} onClick={() => { setLocationPlotting(true); setPlacement(null); setError(""); }}>Next: Plot camera location →</button></div>}
        <section className={`camera-modal-section camera-modal-details ${placement && placementZone?.zoneId === selectedZoneId ? "ready" : "locked"}`}><span className="camera-modal-step">02 / CAMERA DETAILS</span><div className="camera-modal-fields"><label>Camera name<input value={name} onChange={(event) => setName(event.target.value)} minLength={2} required disabled={Boolean(draft) || !placement || placementZone?.zoneId !== selectedZoneId} /></label><label>Source<input value={labelFor(sourceType)} disabled /></label><label>Coordinate X<input value={placement ? `${toMapPoint(placement, mapSize).xMeters} m` : "Set from map"} readOnly disabled /></label><label>Coordinate Y<input value={placement ? `${toMapPoint(placement, mapSize).yMeters} m` : "Set from map"} readOnly disabled /></label></div><label>Description <small>Optional</small><input value={description} onChange={(event) => setDescription(event.target.value)} disabled={Boolean(draft) || !placement || placementZone?.zoneId !== selectedZoneId} placeholder="What this Camera monitors" /></label><small className="camera-coverage-hint">{draft ? "This placement and Camera identity are saved in the active draft." : cameraCount === 0 ? "The first Camera uses this laptop's Camera." : sourceType === "looped_video" ? "This prototype Camera uses a looped video and starts with monitoring disabled." : "This Camera keeps its current source type during reconfiguration."}</small></section>
      </div>}

      {step === "source" && <div className="camera-registration-page reference-page"><section className="registration-media-workspace"><header><div><span>02 / REFERENCE SOURCE</span><h3>{labelFor(sourceType)}</h3><p>{sourceType === "laptop_camera" ? "Open the laptop Camera and capture a clear frame that shows the full monitoring area." : "Upload the demonstration video, pause on a clear frame, then capture it as the registration reference."}</p></div><b className={sourceReady ? "ready" : ""}>{sourceReady ? "Reference ready" : "Reference required"}</b></header>{sourceType === "laptop_camera" ? <><video ref={webcam} autoPlay muted playsInline className="registration-video" /><div className="registration-inline-actions"><button type="button" onClick={() => void startWebcam()}>Open laptop Camera</button><button type="button" className="primary" onClick={() => void captureWebcam()} disabled={busy}>Capture current frame</button></div></> : <><label className="registration-upload"><strong>{videoFile?.name ?? "Choose a looped video"}</strong><small>MP4, MOV or WebM</small><input type="file" accept="video/mp4,video/quicktime,video/webm" onChange={(event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) void chooseVideo(file); }} /></label>{videoUrl && <><video ref={video} className="registration-video" src={videoUrl} controls playsInline /><button type="button" className="primary registration-capture" disabled={busy || !videoFile} onClick={() => { if (video.current) void captureFrame(video.current, "video-reference.jpg").then(uploadReference).catch((reason) => setError(reason instanceof Error ? reason.message : "The video frame could not be captured.")); }}>Use current frame as reference</button></>}</>}</section><aside className="registration-side-panel"><span>REFERENCE PREVIEW</span>{reference ? <><img src={reference.url} alt="Saved Camera reference" /><strong>Frame stored</strong><small>{reference.width} × {reference.height} pixels</small><p>This exact frame will be used to plot the floor and visible bins.</p></> : <div className="registration-empty"><strong>No reference yet</strong><p>Capture one clear frame before continuing.</p></div>}</aside></div>}

      {step === "plot" && reference && <div className="camera-registration-page plot-page"><section className="registration-media-workspace"><header><div><span>03 / FOOTAGE REGIONS</span><h3>{mode === "floor" ? "Plot the walkable floor." : "Plot visible bins."}</h3><p>{mode === "floor" ? "Only litter detections inside this boundary count toward the Camera workflow." : "Bin regions are optional. Add each physical bin visible in this Camera view."}</p></div><b className={floorReady ? "ready" : ""}>{floorReady ? `${bins.length} bins · floor ready` : "Floor required"}</b></header><PlotCanvas imageUrl={reference.url} width={reference.width} height={reference.height} floor={floor} bins={bins} mode={mode} pending={pending} onPoint={addPoint} /></section><aside className="registration-side-panel region-tools"><span>PLOTTING TOOLS</span><div className="camera-zone-mode"><button type="button" className={mode === "floor" ? "active" : ""} onClick={() => { setMode("floor"); setPending([]); }}><b>Floor region</b><small>Required monitoring boundary</small></button><button type="button" className={mode === "bin" ? "active" : ""} onClick={() => { setMode("bin"); setPending([]); }}><b>Bin region</b><small>{bins.length} registered</small></button></div>{mode === "bin" && <label>Bin display name<input value={binName} onChange={(event) => setBinName(event.target.value)} /></label>}<dl><div><dt>POINTS IN PROGRESS</dt><dd>{pending.length}</dd></div><div><dt>SAVED BINS</dt><dd>{bins.length}</dd></div></dl><div className="registration-tool-actions"><button type="button" onClick={() => setPending((points) => points.slice(0, -1))} disabled={!pending.length}>Undo point</button><button type="button" onClick={() => setPending([])} disabled={!pending.length}>Clear points</button><button type="button" className="primary" onClick={finishPolygon} disabled={!pending.length}>Finish {mode} region</button></div>{bins.length > 0 && <button type="button" className="registration-remove-bin" onClick={() => setBins((items) => items.slice(0, -1))}>Remove last bin</button>}</aside></div>}

      {step === "review" && <div className="camera-registration-page review-page"><section className="registration-media-workspace"><header><div><span>04 / VALIDATE & PUBLISH</span><h3>Registration is ready.</h3><p>Review the Camera placement and detection regions before publishing.</p></div><b className="ready">Validated</b></header>{reference && <PlotCanvas imageUrl={reference.url} width={reference.width} height={reference.height} floor={floor} bins={bins} mode="floor" pending={[]} onPoint={() => undefined} />}</section><aside className="registration-side-panel registration-summary"><span>REGISTRATION SUMMARY</span><dl><div><dt>CAMERA</dt><dd>{name}</dd></div><div><dt>ZONE</dt><dd>{placementZone?.zoneNameSnapshot ?? "Existing placement"}</dd></div><div><dt>SOURCE</dt><dd>{labelFor(sourceType)}</dd></div><div><dt>FLOOR REGION</dt><dd>{floor.length} points</dd></div><div><dt>REGISTERED BINS</dt><dd>{bins.length}</dd></div><div><dt>AFTER PUBLISHING</dt><dd>{sourceType === "looped_video" ? "Monitoring disabled" : "Monitoring enabled"}</dd></div></dl><p>Publishing creates or replaces the operational Camera, its placement, source and registration in one backend operation.</p></aside></div>}

      {error && <p className="camera-modal-error" role="alert">{error}</p>}{note && <p className="camera-registration-note" role="status">{note}</p>}
      <footer className="camera-registration-footer"><p>{step === "location" ? "Place the Camera inside one active Zone. Camera creation remains a draft until Page 4." : step === "source" ? "The reference should show the complete floor area and any bins you want to register." : step === "plot" ? "The floor region is required. Bin regions are optional." : "Publish only after the placement and overlays match the physical Camera view."}</p><div>{step === "location" ? <button type="button" className="outline-button" onClick={close}>Cancel</button> : <button type="button" className="outline-button" onClick={goBack} disabled={busy}>← Back</button>}<button type="button" className="primary" onClick={next} disabled={nextDisabled}>{nextLabel}</button></div></footer>
    </section>
  </div>;
}
